package eu.isas.peptideshaker.gui.tabpanels;

import com.compomics.util.experiment.biology.Enzyme;
import com.compomics.util.experiment.biology.PTM;
import com.compomics.util.experiment.biology.PTMFactory;
import com.compomics.util.experiment.biology.Protein;
import com.compomics.util.experiment.identification.SequenceDataBase;
import com.compomics.util.experiment.identification.matches.PeptideMatch;
import com.compomics.util.experiment.identification.matches.ProteinMatch;
import com.compomics.util.experiment.identification.matches.SpectrumMatch;
import eu.isas.peptideshaker.PeptideShaker;
import eu.isas.peptideshaker.fdrestimation.PosteriorValidationMetrics;
import eu.isas.peptideshaker.fdrestimation.PosteriorValidationPoint;
import eu.isas.peptideshaker.fdrestimation.TargetDecoyMap;
import eu.isas.peptideshaker.fdrestimation.TargetDecoyResults;
import eu.isas.peptideshaker.fdrestimation.TargetDecoySeries;
import eu.isas.peptideshaker.gui.PeptideShakerGUI;
import eu.isas.peptideshaker.myparameters.PSMaps;
import java.awt.Color;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.AxisLocation;
import org.jfree.chart.axis.LogAxis;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.ValueMarker;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.DefaultXYDataset;

/**
 * This panel displays statistical information about the dataset
 *
 * @author vaudel
 */
public class StatsPanel extends javax.swing.JPanel {

    /**
     * The main peptide shaker gui
     */
    private PeptideShakerGUI parent;

    /** Creates new form StatsPanel */
    public StatsPanel(PeptideShakerGUI parent) {

        this.parent = parent;

        initComponents();

        // Initialize pep plot
        LogAxis scoreAxis = new LogAxis("probabilistic score");
        NumberAxis pAxis = new NumberAxis("Confidence [%]");
        pAxis.setAutoRangeIncludesZero(true);
        pepPlot.setDomainAxis(scoreAxis);
        pepPlot.setRangeAxis(0, pAxis);
        pepPlot.setRangeAxisLocation(0, AxisLocation.TOP_OR_LEFT);
        pepPlot.setRangeAxisLocation(1, AxisLocation.BOTTOM_OR_RIGHT);
        confidenceMarker.setPaint(Color.red);
        pepPlot.addDomainMarker(confidenceMarker);

        // Initialize FDR/FNR plot
        NumberAxis fdrAxis = new NumberAxis("FDR - FNR [%]");
        fdrAxis.setAutoRangeIncludesZero(true);
        fdrPlot.setDomainAxis(scoreAxis);
        fdrPlot.setRangeAxis(0, fdrAxis);
        fdrPlot.setRangeAxisLocation(0, AxisLocation.TOP_OR_LEFT);
        fdrPlot.setRangeAxisLocation(1, AxisLocation.BOTTOM_OR_RIGHT);

        // Initialize benefit/cost plot
        NumberAxis benefitAxis = new NumberAxis("Benefit (1-FNR) [%]");
        NumberAxis costAxis = new NumberAxis("Cost (FDR) [%]");
        benefitAxis.setAutoRangeIncludesZero(true);
        costAxis.setAutoRangeIncludesZero(true);
        benefitCostPlot.setDomainAxis(costAxis);
        benefitCostPlot.setRangeAxis(0, benefitAxis);
        benefitCostPlot.setRangeAxisLocation(0, AxisLocation.TOP_OR_LEFT);
        benefitCostPlot.setRangeAxisLocation(1, AxisLocation.BOTTOM_OR_RIGHT);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        groupList = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nValidatedClassicalTxt = new javax.swing.JTextField();
        nFPClassicalTxt = new javax.swing.JTextField();
        nTotalTxt = new javax.swing.JTextField();
        fnrClassicalTxt = new javax.swing.JTextField();
        confidenceClassicalTxt = new javax.swing.JTextField();
        fdrClassicalTxt = new javax.swing.JTextField();
        classicalValidationBox = new javax.swing.JCheckBox();
        probaValidationCheck = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nTPClassicalTxt = new javax.swing.JTextField();
        nValidatedProbaTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        confidenceProbaTxt = new javax.swing.JTextField();
        nFPProbaTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fdrProbaTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nTPProbaTxt = new javax.swing.JTextField();
        fnrProbaTxt = new javax.swing.JTextField();
        applyButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nMaxTxt = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        plotTabbedTab = new javax.swing.JTabbedPane();
        pepTab = new javax.swing.JPanel();
        pepPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        sensitivitySlider = new javax.swing.JSlider();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        confidenceSlider = new javax.swing.JSlider();
        jLabel26 = new javax.swing.JLabel();
        windowTxt = new javax.swing.JTextField();
        fdrFnrTab = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        fdrCombo1 = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        fdrSlider1 = new javax.swing.JSlider();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        fdrFnrPanel = new javax.swing.JPanel();
        benefitCostTab = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        fdrCombo2 = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        fdrSlider2 = new javax.swing.JSlider();
        jLabel32 = new javax.swing.JLabel();
        benefitCostPanel = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Group Selection"));

        groupList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Proteins", "Peptides", "PSMs" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        groupList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                groupListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(groupList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Identification summary"));

        jLabel1.setText("# Validated hits:");

        jLabel2.setText("# Total:");

        jLabel3.setText("# FP:");

        jLabel4.setText("FDR:");

        jLabel5.setText("FNR:");

        jLabel6.setText("Confidence threshold:");

        nValidatedClassicalTxt.setEditable(false);

        nFPClassicalTxt.setEditable(false);

        nTotalTxt.setEditable(false);

        fnrClassicalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnrClassicalTxtActionPerformed(evt);
            }
        });

        confidenceClassicalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confidenceClassicalTxtActionPerformed(evt);
            }
        });

        fdrClassicalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdrClassicalTxtActionPerformed(evt);
            }
        });

        classicalValidationBox.setText("Classical validation:");
        classicalValidationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classicalValidationBoxActionPerformed(evt);
            }
        });

        probaValidationCheck.setText("Probabilistic Validation:");
        probaValidationCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probaValidationCheckActionPerformed(evt);
            }
        });

        jLabel7.setText("# Validated hits:");

        jLabel8.setText("# FP <=");

        jLabel9.setText("#TP >=");

        jLabel10.setText("# TP:");

        nTPClassicalTxt.setEditable(false);

        nValidatedProbaTxt.setEditable(false);

        jLabel11.setText("Confidence:");

        confidenceProbaTxt.setEditable(false);

        nFPProbaTxt.setEditable(false);

        jLabel12.setText("FDR <=");

        fdrProbaTxt.setEditable(false);

        jLabel13.setText("FNR >=");

        nTPProbaTxt.setEditable(false);

        fnrProbaTxt.setEditable(false);

        applyButton.setText("Apply");
        applyButton.setEnabled(false);
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("%");

        jLabel15.setText("%");

        jLabel16.setText("%");

        jLabel17.setText("%");

        jLabel18.setText("%");

        jLabel19.setText("%");

        jLabel20.setText("Nmax:");

        nMaxTxt.setEditable(false);

        cancelButton.setText("Cancel");
        cancelButton.setEnabled(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(probaValidationCheck)
                    .addComponent(classicalValidationBox)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nTPClassicalTxt)
                                        .addComponent(nFPClassicalTxt)
                                        .addComponent(nValidatedClassicalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nFPProbaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                        .addComponent(nValidatedProbaTxt)
                                        .addComponent(nTPProbaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))))
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(66, 66, 66))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(confidenceClassicalTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(fnrClassicalTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(fdrClassicalTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(confidenceProbaTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(fnrProbaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(fdrProbaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nMaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(applyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(nMaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton)
                    .addComponent(applyButton))
                .addGap(18, 18, 18)
                .addComponent(classicalValidationBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nValidatedClassicalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confidenceClassicalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nFPClassicalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fdrClassicalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnrClassicalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(nTPClassicalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(probaValidationCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nValidatedProbaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confidenceProbaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel19))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(nFPProbaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(nTPProbaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fdrProbaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fnrProbaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addComponent(jLabel17))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        plotTabbedTab.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        pepPanel.setLayout(new javax.swing.BoxLayout(pepPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel21.setText("Confidence Threshold");

        jLabel22.setText("PEP window");

        sensitivitySlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sensitivitySliderMouseReleased(evt);
            }
        });
        sensitivitySlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sensitivitySliderMouseDragged(evt);
            }
        });

        jLabel23.setText("Robustness");

        jLabel24.setText("sensitivity");

        jLabel25.setText("Quantity");

        confidenceSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confidenceSliderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                confidenceSliderMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confidenceSliderMouseExited(evt);
            }
        });
        confidenceSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                confidenceSliderMouseMoved(evt);
            }
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                confidenceSliderMouseDragged(evt);
            }
        });

        jLabel26.setText("Quality");

        windowTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(windowTxt)))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(confidenceSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sensitivitySlider, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel26))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel25))
                        .addGap(5, 5, 5))
                    .addComponent(jLabel26)
                    .addComponent(confidenceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel24)
                        .addComponent(windowTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23)
                    .addComponent(sensitivitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pepTabLayout = new javax.swing.GroupLayout(pepTab);
        pepTab.setLayout(pepTabLayout);
        pepTabLayout.setHorizontalGroup(
            pepTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
            .addComponent(pepPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        pepTabLayout.setVerticalGroup(
            pepTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pepTabLayout.createSequentialGroup()
                .addComponent(pepPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        plotTabbedTab.addTab("PEP estimation", pepTab);

        fdrCombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Classical", "Probabilistic" }));
        fdrCombo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fdrCombo1MouseReleased(evt);
            }
        });
        fdrCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdrCombo1ActionPerformed(evt);
            }
        });

        jLabel27.setText("FDR threshold");

        fdrSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fdrSlider1MouseReleased(evt);
            }
        });
        fdrSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                fdrSlider1MouseDragged(evt);
            }
        });

        jLabel28.setText("Quality");

        jLabel29.setText("Quantity");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fdrCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addGap(30, 30, 30)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fdrSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fdrSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fdrCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27)
                        .addComponent(jLabel28)
                        .addComponent(jLabel29)))
                .addContainerGap())
        );

        fdrFnrPanel.setLayout(new javax.swing.BoxLayout(fdrFnrPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout fdrFnrTabLayout = new javax.swing.GroupLayout(fdrFnrTab);
        fdrFnrTab.setLayout(fdrFnrTabLayout);
        fdrFnrTabLayout.setHorizontalGroup(
            fdrFnrTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fdrFnrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        fdrFnrTabLayout.setVerticalGroup(
            fdrFnrTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fdrFnrTabLayout.createSequentialGroup()
                .addComponent(fdrFnrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        plotTabbedTab.addTab("FDR/FNR estimation", fdrFnrTab);

        fdrCombo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Classical", "Probabilistic" }));
        fdrCombo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fdrCombo2MouseReleased(evt);
            }
        });
        fdrCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdrCombo2ActionPerformed(evt);
            }
        });

        jLabel30.setText("FDR threshold");

        jLabel31.setText("Quantity");

        fdrSlider2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fdrSlider2MouseReleased(evt);
            }
        });
        fdrSlider2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                fdrSlider2MouseDragged(evt);
            }
        });

        jLabel32.setText("Quality");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fdrCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addGap(26, 26, 26)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fdrSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fdrSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fdrCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)
                        .addComponent(jLabel32)
                        .addComponent(jLabel31)))
                .addContainerGap())
        );

        benefitCostPanel.setLayout(new javax.swing.BoxLayout(benefitCostPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout benefitCostTabLayout = new javax.swing.GroupLayout(benefitCostTab);
        benefitCostTab.setLayout(benefitCostTabLayout);
        benefitCostTabLayout.setHorizontalGroup(
            benefitCostTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(benefitCostPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        benefitCostTabLayout.setVerticalGroup(
            benefitCostTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, benefitCostTabLayout.createSequentialGroup()
                .addComponent(benefitCostPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        plotTabbedTab.addTab("Benefit/Cost optimization", benefitCostTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(plotTabbedTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plotTabbedTab, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void groupListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupListMousePressed
        groupSelectionChanged();
    }//GEN-LAST:event_groupListMousePressed

    private void confidenceClassicalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confidenceClassicalTxtActionPerformed
        try {
            lastThreshold = new Double(confidenceClassicalTxt.getText());
            lastThresholdType = 0;
            updateResults();
            updateDisplayedComponents();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please verify the given threshold.", "Import error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_confidenceClassicalTxtActionPerformed

    private void fdrClassicalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdrClassicalTxtActionPerformed
        try {
            lastThreshold = new Double(fdrClassicalTxt.getText());
            lastThresholdType = 1;
            updateResults();
            updateDisplayedComponents();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please verify the given threshold.", "Import error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_fdrClassicalTxtActionPerformed

    private void fnrClassicalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnrClassicalTxtActionPerformed
        try {
            lastThreshold = new Double(fnrClassicalTxt.getText());
            lastThresholdType = 2;
            updateResults();
            updateDisplayedComponents();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please verify the given threshold.", "Import error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_fnrClassicalTxtActionPerformed

    private void fdrCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdrCombo1ActionPerformed
    }//GEN-LAST:event_fdrCombo1ActionPerformed

    private void fdrCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdrCombo2ActionPerformed
    }//GEN-LAST:event_fdrCombo2ActionPerformed

    private void confidenceSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confidenceSliderMouseReleased
        lastThreshold = new Double(confidenceSlider.getValue());
        lastThresholdType = 0;
        updateResults();
        updateDisplayedComponents();
    }//GEN-LAST:event_confidenceSliderMouseReleased

    private void confidenceSliderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confidenceSliderMousePressed
    }//GEN-LAST:event_confidenceSliderMousePressed

    private void confidenceSliderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confidenceSliderMouseExited
    }//GEN-LAST:event_confidenceSliderMouseExited

    private void confidenceSliderMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confidenceSliderMouseMoved
    }//GEN-LAST:event_confidenceSliderMouseMoved

    private void confidenceSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confidenceSliderMouseDragged
        confidenceClassicalTxt.setText(confidenceSlider.getValue() + "");
    }//GEN-LAST:event_confidenceSliderMouseDragged

    private void fdrSlider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fdrSlider1MouseDragged
        fdrClassicalTxt.setText(fdrSlider1.getValue() + "");
    }//GEN-LAST:event_fdrSlider1MouseDragged

    private void fdrSlider2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fdrSlider2MouseDragged
        fdrClassicalTxt.setText(fdrSlider2.getValue() + "");
    }//GEN-LAST:event_fdrSlider2MouseDragged

    private void fdrSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fdrSlider1MouseReleased
        lastThreshold = new Double(fdrSlider1.getValue());
        lastThresholdType = 1;
        fdrSlider2.setValue(fdrSlider1.getValue());
        updateResults();
        updateDisplayedComponents();
    }//GEN-LAST:event_fdrSlider1MouseReleased

    private void fdrSlider2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fdrSlider2MouseReleased
        lastThreshold = new Double(fdrSlider2.getValue());
        lastThresholdType = 1;
        fdrSlider1.setValue(fdrSlider2.getValue());
        updateResults();
        updateDisplayedComponents();
    }//GEN-LAST:event_fdrSlider2MouseReleased

    private void windowTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowTxtActionPerformed
        try {
            Integer newWindow = new Integer(windowTxt.getText());
            currentTargetDecoyMap.setWindowSize(newWindow);
            currentTargetDecoyMap.estimateProbabilities();
            targetDecoySeries = currentTargetDecoyMap.getTargetDecoySeries();
            updateResults();
            updateDisplayedComponents();
            modifiedMaps.put(groupList.getSelectedIndex(), true);
            applyButton.setEnabled(true);
            cancelButton.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please verify the given window size.", "Import error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_windowTxtActionPerformed

    private void sensitivitySliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sensitivitySliderMouseDragged
        Double newWindow = Math.pow(10, sensitivitySlider.getValue() / 50.0 - 1) * currentTargetDecoyMap.getnMax();
        windowTxt.setText(newWindow.intValue() + "");
    }//GEN-LAST:event_sensitivitySliderMouseDragged

    private void sensitivitySliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sensitivitySliderMouseReleased
        windowTxtActionPerformed(null);
    }//GEN-LAST:event_sensitivitySliderMouseReleased

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        if (groupList.getSelectedIndex() == 0) {
            applyProteins();
        } else if (peptideMap.keySet().contains(groupList.getSelectedIndex())) {
            recalculateProteins();
        } else {
            recalculatePeptidesAndProteins();
        }
        applyButton.setEnabled(false);
        cancelButton.setEnabled(false);
    }//GEN-LAST:event_applyButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        windowTxt.setText(currentTargetDecoyMap.getnMax() + "");
        windowTxtActionPerformed(null);
        applyButton.setEnabled(false);
        cancelButton.setEnabled(false);
        modifiedMaps.put(groupList.getSelectedIndex(), false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void fdrCombo1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fdrCombo1MouseReleased
        TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();
        if (fdrCombo1.getSelectedIndex() == 0) {
            currentResults.setClassicalEstimators(true);
        } else {
            currentResults.setClassicalEstimators(false);
        }
        updateResults();
        updateDisplayedComponents();
    }//GEN-LAST:event_fdrCombo1MouseReleased

    private void fdrCombo2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fdrCombo2MouseReleased
        TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();
        if (fdrCombo2.getSelectedIndex() == 0) {
            currentResults.setClassicalEstimators(true);
        } else {
            currentResults.setClassicalEstimators(false);
        }
        updateResults();
        updateDisplayedComponents();
    }//GEN-LAST:event_fdrCombo2MouseReleased

    private void classicalValidationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classicalValidationBoxActionPerformed
        TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();
        if (classicalValidationBox.isSelected()) {
            currentResults.setClassicalValidation(true);
        } else {
            currentResults.setClassicalValidation(false);
        }
        updateResults();
        updateDisplayedComponents();
    }//GEN-LAST:event_classicalValidationBoxActionPerformed

    private void probaValidationCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probaValidationCheckActionPerformed
        TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();
        if (probaValidationCheck.isSelected()) {
            currentResults.setClassicalValidation(false);
        } else {
            currentResults.setClassicalValidation(true);
        }
        updateResults();
        updateDisplayedComponents();
    }//GEN-LAST:event_probaValidationCheckActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JPanel benefitCostPanel;
    private javax.swing.JPanel benefitCostTab;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox classicalValidationBox;
    private javax.swing.JTextField confidenceClassicalTxt;
    private javax.swing.JTextField confidenceProbaTxt;
    private javax.swing.JSlider confidenceSlider;
    private javax.swing.JTextField fdrClassicalTxt;
    private javax.swing.JComboBox fdrCombo1;
    private javax.swing.JComboBox fdrCombo2;
    private javax.swing.JPanel fdrFnrPanel;
    private javax.swing.JPanel fdrFnrTab;
    private javax.swing.JTextField fdrProbaTxt;
    private javax.swing.JSlider fdrSlider1;
    private javax.swing.JSlider fdrSlider2;
    private javax.swing.JTextField fnrClassicalTxt;
    private javax.swing.JTextField fnrProbaTxt;
    private javax.swing.JList groupList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nFPClassicalTxt;
    private javax.swing.JTextField nFPProbaTxt;
    private javax.swing.JTextField nMaxTxt;
    private javax.swing.JTextField nTPClassicalTxt;
    private javax.swing.JTextField nTPProbaTxt;
    private javax.swing.JTextField nTotalTxt;
    private javax.swing.JTextField nValidatedClassicalTxt;
    private javax.swing.JTextField nValidatedProbaTxt;
    private javax.swing.JPanel pepPanel;
    private javax.swing.JPanel pepTab;
    private javax.swing.JTabbedPane plotTabbedTab;
    private javax.swing.JCheckBox probaValidationCheck;
    private javax.swing.JSlider sensitivitySlider;
    private javax.swing.JTextField windowTxt;
    // End of variables declaration//GEN-END:variables
    /**
     * the currently displayed Target Decoy map
     */
    private TargetDecoyMap currentTargetDecoyMap;
    /**
     * The Target Decoy metrics series of the currently displayed map
     */
    private TargetDecoySeries targetDecoySeries;
    /**
     * the psms map: # in the list -> map key
     */
    private HashMap<Integer, Integer> psmMap = new HashMap<Integer, Integer>();
    /**
     * The peptide map: # in the list -> map key
     */
    private HashMap<Integer, String> peptideMap = new HashMap<Integer, String>();
    /**
     * The PEP plot
     */
    private XYPlot pepPlot = new XYPlot();
    /**
     * The FDR/FNR plot
     */
    private XYPlot fdrPlot = new XYPlot();
    /**
     * The Benefit/cost plot
     */
    private XYPlot benefitCostPlot = new XYPlot();
    /**
     * The last threshold input
     */
    private double lastThreshold = 95;
    /**
     * The last threshold type
     * 0 -> confidence
     * 1 -> FDR
     * 2 -> FNR
     */
    private int lastThresholdType = 0;
    /**
     * The confidence threshold marker
     */
    private ValueMarker confidenceMarker = new ValueMarker(1);
    /**
     * Map keeping track of probabilities modifications
     */
    private HashMap<Integer, Boolean> modifiedMaps = new HashMap<Integer, Boolean>();
    /**
     * Metrics and methods used for posterior validation of PSMs and peptides
     */
    private PosteriorValidationMetrics posteriorValidationMetrics = new PosteriorValidationMetrics();
    /**
     * Boolean indicating that results are displayed
     */
    private boolean resultDisplayed = false;

    /**
     * This method displays results on the panel
     */
    public void displayResults() {
        resultDisplayed = true;
        estimatePossibilities();

        PSMaps pSMaps = new PSMaps();
        pSMaps = (PSMaps) parent.getIdentification().getUrParam(pSMaps);
        ArrayList<String> peptideKeys = pSMaps.getPeptideSpecificMap().getKeys();
        HashMap<Integer, String> psmKeys = pSMaps.getPsmSpecificMap().getKeys();

        int nMaps = 3 + peptideKeys.size() + psmKeys.size();
        String[] listContent = new String[nMaps];
        listContent[0] = "Proteins";
        modifiedMaps.put(0, false);
        listContent[1] = "Peptides";
        int cpt = 2;
        for (String pepitdeKey : peptideKeys) {
            peptideMap.put(cpt, pepitdeKey);
            listContent[cpt] = "    " + pepitdeKey;
            modifiedMaps.put(cpt, false);
            cpt++;
        }
        listContent[cpt] = "PSMs";
        cpt++;
        for (Integer psmKey : psmKeys.keySet()) {
            psmMap.put(cpt, psmKey);
            listContent[cpt] = "    " + psmKeys.get(psmKey);
            modifiedMaps.put(cpt, false);
            cpt++;
        }
        groupList.setListData(listContent);
        groupList.setSelectedIndex(0);

        groupSelectionChanged();
    }

    /**
     * Method called whenever a new group selection occurred
     */
    private void groupSelectionChanged() {
        PSMaps pSMaps = new PSMaps();
        pSMaps = (PSMaps) parent.getIdentification().getUrParam(pSMaps);
        int selectedGroup = groupList.getSelectedIndex();
        if (selectedGroup == 0) {
            currentTargetDecoyMap = pSMaps.getProteinMap().getTargetDecoyMap();
            boolean found = false;
            for (int key : psmMap.keySet()) {
                if (modifiedMaps.get(key)) {
                    found = true;
                    break;
                }
            }
            if (found) {
                int outcome = JOptionPane.showConfirmDialog(this, "Probabilities modifications at the PSM level will influence protein results. Recalculate probabilities?", "non applied changes", JOptionPane.YES_NO_OPTION);
                if (outcome == JOptionPane.YES_OPTION) {
                    recalculatePeptidesAndProteins();
                }
            } else {
                for (int key : peptideMap.keySet()) {
                    if (modifiedMaps.get(key)) {
                        found = true;
                        break;
                    }
                }
                if (found) {
                    int outcome = JOptionPane.showConfirmDialog(this, "Probabilities modifications at the peptide level will influence protein results. Recalculate probabilities?", "non applied changes", JOptionPane.YES_NO_OPTION);
                    if (outcome == JOptionPane.YES_OPTION) {
                        recalculateProteins();
                    }
                }
            }
        } else if (peptideMap.containsKey(selectedGroup)) {
            currentTargetDecoyMap = pSMaps.getPeptideSpecificMap().getTargetDecoyMap(peptideMap.get(selectedGroup));
            boolean found = false;
            for (int key : psmMap.keySet()) {
                if (modifiedMaps.get(key)) {
                    found = true;
                    break;
                }
            }
            if (found) {
                int outcome = JOptionPane.showConfirmDialog(this, "Probabilities modifications at the PSM level will influence peptide results. Recalculate probabilities?", "non applied changes", JOptionPane.YES_NO_OPTION);
                if (outcome == JOptionPane.YES_OPTION) {
                    recalculatePeptidesAndProteins();
                }
            }
        } else if (psmMap.containsKey(selectedGroup)) {
            currentTargetDecoyMap = pSMaps.getPsmSpecificMap().getTargetDecoyMap(psmMap.get(selectedGroup));
        } else if (selectedGroup == peptideMap.size()) {
            clearScreen();
            int peptideSpaceSize = 0;
            double nTPTotal = 0;
            for (String peptideSelection : peptideMap.values()) {
                currentTargetDecoyMap = pSMaps.getPeptideSpecificMap().getTargetDecoyMap(peptideSelection);
                TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();
                if (currentResults.getConfidenceLimit() == -1) {
                    currentResults.setConfidenceLimit(95);
                    currentTargetDecoyMap.getTargetDecoySeries().getConfidenceResults(currentResults);
                }
                double proteinScore = pSMaps.getProteinMap().getTargetDecoyMap().getTargetDecoyResults().getScoreLimit();
                PosteriorValidationPoint posteriorValidationPoint = posteriorValidationMetrics.getResults(proteinScore);
                peptideSpaceSize = posteriorValidationPoint.peptideSpaceSize;
                nTPTotal += currentResults.getnTPTotal();
            }
            BigDecimal p = BigDecimal.ONE;
            p = p.divide(new BigDecimal(posteriorValidationMetrics.getSearchSpace()), BigDecimal.ROUND_HALF_DOWN);
            BigDecimal nFP = new BigDecimal(peptideSpaceSize);
            nFP = nFP.multiply(p);
            BigDecimal nTP = new BigDecimal(peptideSpaceSize);
            nTP = nTP.subtract(nFP);
            BigDecimal fdr = nFP.divide(new BigDecimal(peptideSpaceSize));

            probaValidationCheck.setSelected(false);
            classicalValidationBox.setSelected(false);
            nTotalTxt.setText(nTPTotal + "");
            probaValidationCheck.setEnabled(true);
            nValidatedProbaTxt.setEnabled(true);
            nFPProbaTxt.setEnabled(true);
            nTPProbaTxt.setEnabled(true);
            confidenceProbaTxt.setEnabled(true);
            fdrProbaTxt.setEnabled(true);
            fnrProbaTxt.setEnabled(true);
            nValidatedProbaTxt.setText(peptideSpaceSize + "");
            nFPProbaTxt.setText(nFP + "");
            nTPProbaTxt.setText(nTP + "");
            confidenceProbaTxt.setText(p.toEngineeringString());
            fdrProbaTxt.setText(fdr + "");
            try {
                BigDecimal fnr = new BigDecimal(nTPTotal);
                fnr = fnr.subtract(nTP);
                fnr = fnr.divide(new BigDecimal(nTPTotal), BigDecimal.ROUND_HALF_DOWN);
                fnr = fnr.multiply(new BigDecimal(100));
                fnrProbaTxt.setText(fnr + "");
            } catch (Exception e) {
                fnrProbaTxt.setText("");
            }
            applyButton.setEnabled(false);
            cancelButton.setEnabled(false);
            return;
        } else {
            clearScreen();
            int psmSpaceSize = 0;
            double nTPTotal = 0;
            for (int psmSelection : psmMap.values()) {
                currentTargetDecoyMap = pSMaps.getPsmSpecificMap().getTargetDecoyMap(psmSelection);
                TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();
                if (currentResults.getConfidenceLimit() == -1) {
                    currentResults.setConfidenceLimit(95);
                    currentTargetDecoyMap.getTargetDecoySeries().getConfidenceResults(currentResults);
                }
                double proteinScore = pSMaps.getProteinMap().getTargetDecoyMap().getTargetDecoyResults().getScoreLimit();
                PosteriorValidationPoint posteriorValidationPoint = posteriorValidationMetrics.getResults(proteinScore);
                psmSpaceSize = posteriorValidationPoint.psmSpaceSize;
                nTPTotal += currentResults.getnTPTotal();
            }
            BigDecimal p = BigDecimal.ONE;
            p = p.divide(new BigDecimal(posteriorValidationMetrics.getSearchSpace()), BigDecimal.ROUND_HALF_DOWN);
            BigDecimal nFP = new BigDecimal(psmSpaceSize);
            nFP = nFP.multiply(p);
            BigDecimal nTP = new BigDecimal(psmSpaceSize);
            nTP = nTP.subtract(nFP);
            BigDecimal fdr = nFP.divide(new BigDecimal(psmSpaceSize));

            probaValidationCheck.setSelected(false);
            classicalValidationBox.setSelected(false);
            nTotalTxt.setText(nTPTotal + "");
            probaValidationCheck.setEnabled(true);
            nValidatedProbaTxt.setEnabled(true);
            nFPProbaTxt.setEnabled(true);
            nTPProbaTxt.setEnabled(true);
            confidenceProbaTxt.setEnabled(true);
            fdrProbaTxt.setEnabled(true);
            fnrProbaTxt.setEnabled(true);
            nValidatedProbaTxt.setText(psmSpaceSize + "");
            nFPProbaTxt.setText(nFP + "");
            nTPProbaTxt.setText(nTP + "");
            confidenceProbaTxt.setText(p.toEngineeringString());
            fdrProbaTxt.setText(fdr + "");
            try {
                BigDecimal fnr = new BigDecimal(nTPTotal);
                fnr = fnr.subtract(nTP);
                fnr = fnr.divide(new BigDecimal(nTPTotal), BigDecimal.ROUND_HALF_DOWN);
                fnr = fnr.multiply(new BigDecimal(100));
                fnrProbaTxt.setText(fnr + "");
            } catch (Exception e) {
                fnrProbaTxt.setText("");
            }
            applyButton.setEnabled(false);
            cancelButton.setEnabled(false);
            return;
        }
        applyButton.setEnabled(modifiedMaps.get(groupList.getSelectedIndex()));
        cancelButton.setEnabled(modifiedMaps.get(groupList.getSelectedIndex()));
        nMaxTxt.setText(currentTargetDecoyMap.getnMax() + "");
        targetDecoySeries = currentTargetDecoyMap.getTargetDecoySeries();
        TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();
        if (currentResults.getConfidenceLimit() == -1) {
            if (currentTargetDecoyMap.suspiciousInput()) {
                currentResults.setClassicalEstimators(true);
            } else {
                currentResults.setClassicalEstimators(false);
            }
            probaValidationCheck.setSelected(false);
            currentResults.setClassicalValidation(true);
            currentResults.setConfidenceLimit(lastThreshold);
            targetDecoySeries.getConfidenceResults(currentResults);
            if (groupList.getSelectedIndex() == 0) {
                classicalValidationBox.setSelected(true);
            } else {
                classicalValidationBox.setSelected(false);
                probaValidationCheck.setSelected(true);
                currentResults.setClassicalValidation(false);
            }
        }
        updateDisplayedComponents();
    }

    /**
     * Updates the displayed results whenever a new threshold is given
     */
    private void updateResults() {
        TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();
        if (lastThresholdType == 0) {
            currentResults.setConfidenceLimit(lastThreshold);
            targetDecoySeries.getConfidenceResults(currentResults);
        } else if (lastThresholdType == 1) {
            currentResults.setFdrLimit(lastThreshold);
            targetDecoySeries.getFDRResults(currentResults);
        } else if (lastThresholdType == 2) {
            currentResults.setFnrLimit(lastThreshold);
            targetDecoySeries.getFNRResults(currentResults);
        }
        if (groupList.getSelectedIndex() == 0) {
            double proteinScore = currentResults.getScoreLimit();
            PosteriorValidationPoint posteriorValidationPoint = posteriorValidationMetrics.getResults(proteinScore);
            if (posteriorValidationPoint.peptideP1 > 0
                    || posteriorValidationPoint.psmP1 > 0) {
                JOptionPane.showConfirmDialog(this, "Some Peptides/PSMs were validated with a PEP of 1.", "Validation Alert", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    /**
     * Updates the updates the different components of the gui with the new results
     * @param map boolean indicating whether a map is present
     */
    private void updateDisplayedComponents() {
        TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();
        nTotalTxt.setText(currentResults.getnTPTotal() + "");
        nValidatedClassicalTxt.setText(currentResults.getN() + "");
        nFPClassicalTxt.setText(currentResults.getnFP() + "");
        nTPClassicalTxt.setText(currentResults.getnTP() + "");
        confidenceClassicalTxt.setText(currentResults.getConfidenceLimit() + "");
        fdrClassicalTxt.setText(currentResults.getFdrLimit() + "");
        fnrClassicalTxt.setText(currentResults.getFnrLimit() + "");
        confidenceSlider.setValue(currentResults.getConfidenceLimit().intValue());
        fdrSlider1.setValue(currentResults.getFdrLimit().intValue());
        fdrSlider2.setValue(currentResults.getFdrLimit().intValue());
        windowTxt.setText(currentTargetDecoyMap.getWindowSize() + "");
        Double newPosition = 50 * (Math.log10(currentTargetDecoyMap.getWindowSize() / (double) currentTargetDecoyMap.getnMax()) + 1);
        sensitivitySlider.setValue(newPosition.intValue());

        PSMaps pSMaps = new PSMaps();
        pSMaps = (PSMaps) parent.getIdentification().getUrParam(pSMaps);
        double proteinScore = pSMaps.getProteinMap().getTargetDecoyMap().getTargetDecoyResults().getScoreLimit();
        PosteriorValidationPoint posteriorValidationPoint = posteriorValidationMetrics.getResults(proteinScore);
        BigDecimal p = BigDecimal.ONE;
        p = p.divide(new BigDecimal(posteriorValidationMetrics.getSearchSpace()), BigDecimal.ROUND_HALF_DOWN);
        if (groupList.getSelectedIndex() == 0) {
            probaValidationCheck.setEnabled(false);
            nValidatedProbaTxt.setEnabled(false);
            nFPProbaTxt.setEnabled(false);
            nTPProbaTxt.setEnabled(false);
            confidenceProbaTxt.setEnabled(false);
            fdrProbaTxt.setEnabled(false);
            fnrProbaTxt.setEnabled(false);
            nValidatedProbaTxt.setText("");
            nFPProbaTxt.setText("");
            nTPProbaTxt.setText("");
            confidenceProbaTxt.setText("");
            fdrProbaTxt.setText("");
            fnrProbaTxt.setText("");
        } else if (peptideMap.containsKey(groupList.getSelectedIndex())) {
            String peptideKey = peptideMap.get(groupList.getSelectedIndex());
            BigDecimal nFP = new BigDecimal(posteriorValidationPoint.specificPeptideSpaceSize.get(peptideKey));
            nFP = nFP.multiply(p);
            BigDecimal nTP = new BigDecimal(posteriorValidationPoint.specificPeptideSpaceSize.get(peptideKey));
            nTP = nTP.subtract(nFP);
            BigDecimal fdr = nFP.divide(new BigDecimal(posteriorValidationPoint.specificPeptideSpaceSize.get(peptideKey)));

            probaValidationCheck.setEnabled(true);
            nValidatedProbaTxt.setEnabled(true);
            nFPProbaTxt.setEnabled(true);
            nTPProbaTxt.setEnabled(true);
            confidenceProbaTxt.setEnabled(true);
            fdrProbaTxt.setEnabled(true);
            fnrProbaTxt.setEnabled(true);
            nValidatedProbaTxt.setText(posteriorValidationPoint.specificPeptideSpaceSize.get(peptideKey) + "");
            nFPProbaTxt.setText(nFP + "");
            nTPProbaTxt.setText(nTP + "");
            confidenceProbaTxt.setText(p.toEngineeringString());
            fdrProbaTxt.setText(fdr + "");
            try {
                BigDecimal fnr = new BigDecimal(currentResults.getnTPTotal());
                fnr = fnr.subtract(nTP);
                fnr = fnr.divide(new BigDecimal(currentResults.getnTPTotal()), BigDecimal.ROUND_HALF_DOWN);
                fnr = fnr.multiply(new BigDecimal(100));
                fnrProbaTxt.setText(fnr + "");
            } catch (Exception e) {
                fnrProbaTxt.setText("");
            }
        } else if (psmMap.containsKey(groupList.getSelectedIndex())) {
            int psmKey = psmMap.get(groupList.getSelectedIndex());
            BigDecimal nFP = new BigDecimal(posteriorValidationPoint.specificPsmSpaceSize.get(psmKey));
            nFP = nFP.multiply(p);
            BigDecimal nTP = new BigDecimal(posteriorValidationPoint.specificPsmSpaceSize.get(psmKey));
            nTP = nTP.subtract(nFP);
            BigDecimal fdr = nFP.divide(new BigDecimal(posteriorValidationPoint.specificPsmSpaceSize.get(psmKey)));

            probaValidationCheck.setEnabled(true);
            nValidatedProbaTxt.setEnabled(true);
            nFPProbaTxt.setEnabled(true);
            nTPProbaTxt.setEnabled(true);
            confidenceProbaTxt.setEnabled(true);
            fdrProbaTxt.setEnabled(true);
            fnrProbaTxt.setEnabled(true);
            nValidatedProbaTxt.setText(posteriorValidationPoint.specificPsmSpaceSize.get(psmKey) + "");
            nFPProbaTxt.setText(nFP + "");
            nTPProbaTxt.setText(nTP + "");
            confidenceProbaTxt.setText(p + "");
            fdrProbaTxt.setText(fdr + "");
            try {
                BigDecimal fnr = new BigDecimal(currentResults.getnTPTotal());
                fnr = fnr.subtract(nTP);
                fnr = fnr.divide(new BigDecimal(currentResults.getnTPTotal()), BigDecimal.ROUND_HALF_DOWN);
                fnr = fnr.multiply(new BigDecimal(100));
                fnrProbaTxt.setText(fnr + "");
            } catch (Exception e) {
                fnrProbaTxt.setText("");
            }
        } else {
            probaValidationCheck.setEnabled(true);
            nValidatedProbaTxt.setEnabled(true);
            nFPProbaTxt.setEnabled(true);
            nTPProbaTxt.setEnabled(true);
            confidenceProbaTxt.setEnabled(true);
            fdrProbaTxt.setEnabled(true);
            fnrProbaTxt.setEnabled(true);
            nValidatedProbaTxt.setText("");
            nFPProbaTxt.setText("");
            nTPProbaTxt.setText("");
            confidenceProbaTxt.setText("");
            fdrProbaTxt.setText("");
            fnrProbaTxt.setText("");
        }
        if (currentResults.isClassicalEstimators()) {
            nTotalTxt.setEnabled(false);
            fnrClassicalTxt.setEnabled(false);
            fdrCombo1.setSelectedIndex(0);
            fdrCombo2.setSelectedIndex(0);
        } else {
            nTotalTxt.setEnabled(true);
            fnrClassicalTxt.setEnabled(true);
            fdrCombo1.setSelectedIndex(1);
            fdrCombo2.setSelectedIndex(1);
        }
        if (currentResults.isClassicalValidation()) {
            classicalValidationBox.setSelected(true);
            probaValidationCheck.setSelected(false);
            confidenceSlider.setEnabled(true);
            fdrSlider1.setEnabled(true);
            fdrSlider2.setEnabled(true);
        } else {
            classicalValidationBox.setSelected(false);
            probaValidationCheck.setSelected(true);
            confidenceSlider.setEnabled(false);
            fdrSlider1.setEnabled(false);
            fdrSlider2.setEnabled(false);
        }
        updateCharts();
    }

    /**
     * Updates the statistical charts
     */
    private void updateCharts() {
        updatePepChart();
        updateFDRChart();
        updateCostBenefitChart();
        setMarkers();
        pepPanel.revalidate();
        pepPanel.repaint();
        fdrFnrPanel.revalidate();
        fdrFnrPanel.repaint();
        benefitCostPanel.revalidate();
        benefitCostPanel.repaint();
    }

    /**
     * Sets the threshold marker
     */
    private void setMarkers() {

        TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();

        confidenceMarker.setValue(currentResults.getScoreLimit());

        double[] score = {currentResults.getScoreLimit()};
        double[] fdr = {currentResults.getFdrLimit()};
        double[] fnr = {currentResults.getFnrLimit()};
        double[] benefit = {100 - currentResults.getFnrLimit()};

        DefaultXYDataset fdrData = new DefaultXYDataset();
        double[][] fdrSeries = {score, fdr};
        fdrData.addSeries("retained FDR ", fdrSeries);
        fdrPlot.setDataset(3, fdrData);
        fdrPlot.mapDatasetToRangeAxis(3, 0);

        DefaultXYDataset probaFnrData = new DefaultXYDataset();
        double[][] probaFnrSeries = {score, fnr};
        probaFnrData.addSeries("retained FNR ", probaFnrSeries);
        fdrPlot.setDataset(4, probaFnrData);
        fdrPlot.mapDatasetToRangeAxis(4, 0);

        XYLineAndShapeRenderer fdrRendrer = new XYLineAndShapeRenderer();
        fdrRendrer.setSeriesShapesVisible(0, true);
        fdrRendrer.setSeriesLinesVisible(0, false);
        if (currentResults.isClassicalEstimators()) {
            fdrRendrer.setSeriesPaint(0, Color.blue);
        } else {
            fdrRendrer.setSeriesPaint(0, Color.green);
        }
        fdrPlot.setRenderer(3, fdrRendrer);

        XYLineAndShapeRenderer probaFnrRendrer = new XYLineAndShapeRenderer();
        probaFnrRendrer.setSeriesShapesVisible(0, true);
        probaFnrRendrer.setSeriesLinesVisible(0, false);
        probaFnrRendrer.setSeriesPaint(0, Color.RED);
        fdrPlot.setRenderer(4, probaFnrRendrer);


        DefaultXYDataset benefitData = new DefaultXYDataset();
        double[][] benefitSeries = {fdr, benefit};
        benefitData.addSeries("retained benefit/cost", benefitSeries);
        benefitCostPlot.setDataset(1, benefitData);
        benefitCostPlot.mapDatasetToRangeAxis(1, 0);

        XYLineAndShapeRenderer benefitRendrer = new XYLineAndShapeRenderer();
        benefitRendrer.setSeriesShapesVisible(0, true);
        benefitRendrer.setSeriesLinesVisible(0, false);
        benefitRendrer.setSeriesPaint(0, Color.blue);
        benefitCostPlot.setRenderer(1, benefitRendrer);

    }

    /**
     * Updates the pep chart
     */
    private void updatePepChart() {
        DefaultXYDataset pepData = new DefaultXYDataset();
        double[][] pepSeries = {targetDecoySeries.getScores(), targetDecoySeries.getConfidence()};
        pepData.addSeries("Confidence", pepSeries);
        pepPlot.setDataset(0, pepData);
        pepPlot.mapDatasetToRangeAxis(0, 0);

        XYLineAndShapeRenderer pepRendrer = new XYLineAndShapeRenderer();
        pepRendrer.setSeriesShapesVisible(0, false);
        pepRendrer.setSeriesLinesVisible(0, true);
        pepRendrer.setSeriesPaint(0, Color.blue);
        pepPlot.setRenderer(0, pepRendrer);

        JFreeChart pepChart = new JFreeChart(pepPlot);
        ChartPanel pepChartPanel = new ChartPanel(pepChart);

        pepPanel.removeAll();
        pepPanel.add(pepChartPanel);
        pepPanel.revalidate();
        pepPanel.repaint();
    }

    /**
     * Updates the FDR chart
     */
    private void updateFDRChart() {
        DefaultXYDataset classicalFdrData = new DefaultXYDataset();
        double[][] classicalFdrSeries = {targetDecoySeries.getScores(), targetDecoySeries.getClassicalFDR()};
        classicalFdrData.addSeries("Classical FDR ", classicalFdrSeries);
        fdrPlot.setDataset(0, classicalFdrData);
        fdrPlot.mapDatasetToRangeAxis(0, 0);

        DefaultXYDataset probaFdrData = new DefaultXYDataset();
        double[][] probaFdrSeries = {targetDecoySeries.getScores(), targetDecoySeries.getProbaFDR()};
        probaFdrData.addSeries("Probabilistic FDR ", probaFdrSeries);
        fdrPlot.setDataset(1, probaFdrData);
        fdrPlot.mapDatasetToRangeAxis(1, 0);

        DefaultXYDataset probaFnrData = new DefaultXYDataset();
        double[][] probaFnrSeries = {targetDecoySeries.getScores(), targetDecoySeries.getProbaFNR()};
        probaFnrData.addSeries("Probabilistic FNR ", probaFnrSeries);
        fdrPlot.setDataset(2, probaFnrData);
        fdrPlot.mapDatasetToRangeAxis(2, 0);

        XYLineAndShapeRenderer classicalFdrRendrer = new XYLineAndShapeRenderer();
        classicalFdrRendrer.setSeriesShapesVisible(0, false);
        classicalFdrRendrer.setSeriesLinesVisible(0, true);
        classicalFdrRendrer.setSeriesPaint(0, Color.blue);
        fdrPlot.setRenderer(0, classicalFdrRendrer);

        XYLineAndShapeRenderer probaFdrRendrer = new XYLineAndShapeRenderer();
        probaFdrRendrer.setSeriesShapesVisible(0, false);
        probaFdrRendrer.setSeriesLinesVisible(0, true);
        probaFdrRendrer.setSeriesPaint(0, Color.GREEN);
        fdrPlot.setRenderer(1, probaFdrRendrer);

        XYLineAndShapeRenderer probaFnrRendrer = new XYLineAndShapeRenderer();
        probaFnrRendrer.setSeriesShapesVisible(0, false);
        probaFnrRendrer.setSeriesLinesVisible(0, true);
        probaFnrRendrer.setSeriesPaint(0, Color.RED);
        fdrPlot.setRenderer(2, probaFnrRendrer);

        JFreeChart fdrChart = new JFreeChart(fdrPlot);
        ChartPanel fdrChartPanel = new ChartPanel(fdrChart);

        fdrFnrPanel.removeAll();
        fdrFnrPanel.add(fdrChartPanel);
        fdrFnrPanel.revalidate();
        fdrFnrPanel.repaint();
    }

    /**
     * Updates the cost benefit chart
     */
    private void updateCostBenefitChart() {
        DefaultXYDataset benefitData = new DefaultXYDataset();
        double[][] benefitSeries = {targetDecoySeries.getProbaFDR(), targetDecoySeries.getProbaBenefit()};
        benefitData.addSeries("Benefit", benefitSeries);
        benefitCostPlot.setDataset(0, benefitData);
        benefitCostPlot.mapDatasetToRangeAxis(0, 0);

        XYLineAndShapeRenderer benefitRendrer = new XYLineAndShapeRenderer();
        benefitRendrer.setSeriesShapesVisible(0, false);
        benefitRendrer.setSeriesLinesVisible(0, true);
        benefitRendrer.setSeriesPaint(0, Color.blue);
        benefitCostPlot.setRenderer(0, benefitRendrer);

        JFreeChart benefitCostChart = new JFreeChart(benefitCostPlot);
        ChartPanel benefitCostChartPanel = new ChartPanel(benefitCostChart);
        benefitCostPanel.removeAll();
        benefitCostPanel.add(benefitCostChartPanel);
        benefitCostPanel.revalidate();
        benefitCostPanel.repaint();
    }

    /**
     * Removes the charts
     */
    private void clearCharts() {
        pepPanel.removeAll();
        pepPanel.revalidate();
        pepPanel.repaint();
        fdrFnrPanel.removeAll();
        fdrFnrPanel.revalidate();
        fdrFnrPanel.repaint();
        benefitCostPanel.removeAll();
        benefitCostPanel.revalidate();
        benefitCostPanel.repaint();
    }

    /**
     * Clears the GUI
     */
    private void clearScreen() {
        nTotalTxt.setText("");
        nValidatedClassicalTxt.setText("");
        nFPClassicalTxt.setText("");
        nTPClassicalTxt.setText("");
        confidenceClassicalTxt.setText("");
        fdrClassicalTxt.setText("");
        fnrClassicalTxt.setText("");
        probaValidationCheck.setEnabled(true);
        nValidatedProbaTxt.setText("");
        nFPProbaTxt.setText("");
        nTPProbaTxt.setText("");
        confidenceProbaTxt.setText("");
        fdrProbaTxt.setText("");
        fnrProbaTxt.setText("");
        nMaxTxt.setText("");
        clearCharts();
    }

    /**
     * recalculates probabilities for peptides and proteins
     */
    private void recalculatePeptidesAndProteins() {
        PSMaps pSMaps = new PSMaps();
        pSMaps = (PSMaps) parent.getIdentification().getUrParam(pSMaps);
        PeptideShaker miniShaker = new PeptideShaker(parent.getExperiment(), parent.getSample(), parent.getReplicateNumber(), pSMaps);
        try {
            miniShaker.spectrumMapChanged();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An identification conflict occured. If you can reproduce the error please contact the developers.", "identification conflict", JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
        }
        for (int key : modifiedMaps.keySet()) {
            modifiedMaps.put(key, false);
        }
    }

    /**
     * Recalculates probabilities for proteins only
     */
    private void recalculateProteins() {
        PSMaps pSMaps = new PSMaps();
        pSMaps = (PSMaps) parent.getIdentification().getUrParam(pSMaps);
        PeptideShaker miniShaker = new PeptideShaker(parent.getExperiment(), parent.getSample(), parent.getReplicateNumber(), pSMaps);
        try {
            miniShaker.peptideMapChanged();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An identification conflict occured. If you can reproduce the error please contact the developers.", "identification conflict", JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
        }
        modifiedMaps.put(0, false);
        for (int key : peptideMap.keySet()) {
            modifiedMaps.put(key, false);
        }
    }

    /**
     * Apply the new protein settings
     */
    private void applyProteins() {
        PSMaps pSMaps = new PSMaps();
        pSMaps = (PSMaps) parent.getIdentification().getUrParam(pSMaps);
        PeptideShaker miniShaker = new PeptideShaker(parent.getExperiment(), parent.getSample(), parent.getReplicateNumber(), pSMaps);
        miniShaker.proteinMapChanged();
        modifiedMaps.put(0, false);
    }

    /**
     * Estimates the database and dataset possibilities
     */
    public void estimatePossibilities() {
        if (resultDisplayed) {
        PSMaps pSMaps = new PSMaps();
        pSMaps = (PSMaps) parent.getIdentification().getUrParam(pSMaps);
        posteriorValidationMetrics.estimateDatasetPossibilities(parent.getSearchParameters(), parent.getSequenceDataBase(), parent.getIdentification(), pSMaps.getPeptideSpecificMap(), pSMaps.getPsmSpecificMap());
        posteriorValidationMetrics.estimateDataBasePossibilities(parent.getSearchParameters(), parent.getSequenceDataBase());
        }
    }
}
