package eu.isas.peptideshaker.gui.tabpanels;

import com.compomics.util.Util;
import com.compomics.util.gui.renderers.AlignedListCellRenderer;
import eu.isas.peptideshaker.PeptideShaker;
import eu.isas.peptideshaker.fdrestimation.PosteriorValidationMetrics;
import eu.isas.peptideshaker.fdrestimation.PosteriorValidationPoint;
import eu.isas.peptideshaker.fdrestimation.TargetDecoyMap;
import eu.isas.peptideshaker.fdrestimation.TargetDecoyResults;
import eu.isas.peptideshaker.fdrestimation.TargetDecoySeries;
import eu.isas.peptideshaker.gui.PeptideShakerGUI;
import eu.isas.peptideshaker.myparameters.PSMaps;
import java.awt.BasicStroke;
import java.awt.Color;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.AxisLocation;
import org.jfree.chart.axis.LogAxis;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.DefaultDrawingSupplier;
import org.jfree.chart.plot.ValueMarker;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.DefaultXYDataset;

/**
 * This panel displays statistical information about the dataset
 *
 * @author Marc Vaudel
 * @author Harald Barsnes
 */
public class StatsPanel extends javax.swing.JPanel {

    /**
     * The main peptide shaker gui
     */
    private PeptideShakerGUI peptideShakerGUI;
    /**
     * The default line width for the line plots.
     */
    private final int LINE_WIDTH = 2;

    /**
     * Create a new StatsPanel
     *
     * @param parent the PeptideShaker parent frame.
     */
    public StatsPanel(PeptideShakerGUI parent) {

        this.peptideShakerGUI = parent;

        initComponents();

        // Initialize pep plot
        LogAxis scoreAxis = new LogAxis("Probabilistic Score");
        NumberAxis pAxis = new NumberAxis("Confidence [%]");
        pAxis.setAutoRangeIncludesZero(true);
        pepPlot.setDomainAxis(scoreAxis);
        pepPlot.setRangeAxis(0, pAxis);
        pepPlot.setRangeAxisLocation(0, AxisLocation.TOP_OR_LEFT);
        pepPlot.setRangeAxisLocation(1, AxisLocation.BOTTOM_OR_RIGHT);
        confidenceMarker.setPaint(Color.red);
        confidenceMarker.setStroke(new BasicStroke(LINE_WIDTH));
        pepPlot.addDomainMarker(confidenceMarker);

        // Initialize FDR/FNR plot
        NumberAxis fdrAxis = new NumberAxis("FDR - FNR [%]");
        fdrAxis.setAutoRangeIncludesZero(true);
        fdrPlot.setDomainAxis(scoreAxis);
        fdrPlot.setRangeAxis(0, fdrAxis);
        fdrPlot.setRangeAxisLocation(0, AxisLocation.TOP_OR_LEFT);
        fdrPlot.setRangeAxisLocation(1, AxisLocation.BOTTOM_OR_RIGHT);

        // Initialize benefit/cost plot
        NumberAxis benefitAxis = new NumberAxis("Benefit (1-FNR) [%]");
        NumberAxis costAxis = new NumberAxis("Cost (FDR) [%]");
        benefitAxis.setAutoRangeIncludesZero(true);
        costAxis.setAutoRangeIncludesZero(true);
        benefitCostPlot.setDomainAxis(costAxis);
        benefitCostPlot.setRangeAxis(0, benefitAxis);
        benefitCostPlot.setRangeAxisLocation(0, AxisLocation.TOP_OR_LEFT);
        benefitCostPlot.setRangeAxisLocation(1, AxisLocation.BOTTOM_OR_RIGHT);

        fdrCombo1.setRenderer(new AlignedListCellRenderer(SwingConstants.CENTER));

        formComponentResized(null);
    }

    public void updatePlotSizes() {
        formComponentResized(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        groupList = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nTotalTxt = new javax.swing.JTextField();
        applyButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        nMaxTxt = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nTPClassicalTxt = new javax.swing.JTextField();
        nFPClassicalTxt = new javax.swing.JTextField();
        nValidatedClassicalTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fnrClassicalTxt = new javax.swing.JTextField();
        fdrClassicalTxt = new javax.swing.JTextField();
        confidenceClassicalTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nValidatedProbaTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nTPProbaTxt = new javax.swing.JTextField();
        nFPProbaTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fnrProbaTxt = new javax.swing.JTextField();
        fdrProbaTxt = new javax.swing.JTextField();
        confidenceProbaTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        fdrCombo1 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        windowTxt = new javax.swing.JTextField();
        leftPlotSplitPane = new javax.swing.JSplitPane();
        pepPanel = new javax.swing.JPanel();
        pepChartPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        confidenceSlider = new javax.swing.JSlider();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        sensitivitySlider = new javax.swing.JSlider();
        jLabel23 = new javax.swing.JLabel();
        rightPlotSplitPane = new javax.swing.JSplitPane();
        fdrFnrPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        fdrSlider1 = new javax.swing.JSlider();
        jLabel29 = new javax.swing.JLabel();
        frdFnrChartPanel = new javax.swing.JPanel();
        benefitCostPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        fdrSlider2 = new javax.swing.JSlider();
        jLabel32 = new javax.swing.JLabel();
        benefitCostChartPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Group Selection"));
        jPanel1.setOpaque(false);

        groupList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Proteins", "Peptides", "PSMs" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        groupList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                groupListMousePressed(evt);
            }
        });
        groupList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                groupListKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(groupList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Identification Summary"));
        jPanel2.setOpaque(false);

        jLabel2.setText("# Total:");

        nTotalTxt.setEditable(false);
        nTotalTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        applyButton.setText("Apply");
        applyButton.setEnabled(false);
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        jLabel20.setText("Nmax:");

        nMaxTxt.setEditable(false);
        nMaxTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cancelButton.setText("Cancel");
        cancelButton.setEnabled(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("# Validated Hits:");

        jLabel3.setText("# FP:");

        jLabel10.setText("# TP:");

        nTPClassicalTxt.setEditable(false);
        nTPClassicalTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nFPClassicalTxt.setEditable(false);
        nFPClassicalTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nValidatedClassicalTxt.setEditable(false);
        nValidatedClassicalTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("FNR:");

        jLabel4.setText("FDR:");

        jLabel6.setText("Threshold:");

        fnrClassicalTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fnrClassicalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnrClassicalTxtActionPerformed(evt);
            }
        });

        fdrClassicalTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fdrClassicalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdrClassicalTxtActionPerformed(evt);
            }
        });

        confidenceClassicalTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confidenceClassicalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confidenceClassicalTxtActionPerformed(evt);
            }
        });

        jLabel15.setText("%");

        jLabel14.setText("%");

        jLabel18.setText("%");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nValidatedClassicalTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(nFPClassicalTxt)
                            .addComponent(nTPClassicalTxt)))
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fnrClassicalTxt)
                    .addComponent(fdrClassicalTxt)
                    .addComponent(confidenceClassicalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {confidenceClassicalTxt, fdrClassicalTxt, fnrClassicalTxt, nFPClassicalTxt, nTPClassicalTxt, nValidatedClassicalTxt});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confidenceClassicalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fdrClassicalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fnrClassicalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nValidatedClassicalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nFPClassicalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(nTPClassicalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Classical Validation", jPanel6);

        jPanel7.setOpaque(false);

        jLabel7.setText("# Validated Hits:");

        nValidatedProbaTxt.setEditable(false);
        nValidatedProbaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setText("# FP <=");

        jLabel9.setText("# TP >=");

        nTPProbaTxt.setEditable(false);
        nTPProbaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nFPProbaTxt.setEditable(false);
        nFPProbaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setText("FDR <=");

        jLabel12.setText("FNR >=");

        jLabel11.setText("Threshold:");

        fnrProbaTxt.setEditable(false);
        fnrProbaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fdrProbaTxt.setEditable(false);
        fdrProbaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        confidenceProbaTxt.setEditable(false);
        confidenceProbaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel19.setText("%");

        jLabel16.setText("%");

        jLabel17.setText("%");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nTPProbaTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nFPProbaTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nValidatedProbaTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confidenceProbaTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(fnrProbaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fdrProbaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19))
                .addGap(210, 210, 210))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {confidenceProbaTxt, fdrProbaTxt, fnrProbaTxt, nFPProbaTxt, nTPProbaTxt});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nValidatedProbaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(confidenceProbaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel8)
                    .addComponent(nFPProbaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fdrProbaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9)
                    .addComponent(nTPProbaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnrProbaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Probabilistic Validation", jPanel7);

        fdrCombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Classical", "Probabilistic" }));
        fdrCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdrCombo1ActionPerformed(evt);
            }
        });

        jLabel22.setText("PEP Window:");

        windowTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        windowTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nMaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(applyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(windowTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fdrCombo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(324, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {nMaxTxt, nTotalTxt});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {applyButton, cancelButton});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(nMaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelButton)
                            .addComponent(applyButton))
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(fdrCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(windowTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))))
                .addContainerGap())
        );

        leftPlotSplitPane.setBorder(null);
        leftPlotSplitPane.setDividerLocation(350);
        leftPlotSplitPane.setDividerSize(0);
        leftPlotSplitPane.setResizeWeight(0.5);
        leftPlotSplitPane.setOpaque(false);

        pepPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("PEP"));
        pepPanel.setOpaque(false);

        pepChartPanel.setOpaque(false);
        pepChartPanel.setLayout(new javax.swing.BoxLayout(pepChartPanel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setOpaque(false);

        jLabel25.setText("Quantity");

        confidenceSlider.setToolTipText("Confidence Threshold");
        confidenceSlider.setOpaque(false);
        confidenceSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confidenceSliderMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confidenceSliderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                confidenceSliderMouseReleased(evt);
            }
        });
        confidenceSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                confidenceSliderMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                confidenceSliderMouseMoved(evt);
            }
        });

        jLabel26.setText("Quality");

        jLabel24.setText("Sensitivity");

        sensitivitySlider.setOpaque(false);
        sensitivitySlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sensitivitySliderMouseReleased(evt);
            }
        });
        sensitivitySlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sensitivitySliderMouseDragged(evt);
            }
        });

        jLabel23.setText("Robustness");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sensitivitySlider, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confidenceSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)))
                .addGap(15, 15, 15))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel24, jLabel25});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel23, jLabel26});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel25)
                    .addComponent(confidenceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel24)
                    .addComponent(sensitivitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap())
        );

        javax.swing.GroupLayout pepPanelLayout = new javax.swing.GroupLayout(pepPanel);
        pepPanel.setLayout(pepPanelLayout);
        pepPanelLayout.setHorizontalGroup(
            pepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pepPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pepChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        pepPanelLayout.setVerticalGroup(
            pepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pepPanelLayout.createSequentialGroup()
                .addComponent(pepChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        leftPlotSplitPane.setLeftComponent(pepPanel);

        rightPlotSplitPane.setBorder(null);
        rightPlotSplitPane.setDividerLocation(350);
        rightPlotSplitPane.setDividerSize(0);
        rightPlotSplitPane.setResizeWeight(0.5);
        rightPlotSplitPane.setOpaque(false);

        fdrFnrPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("FDR/FNR"));
        fdrFnrPanel.setOpaque(false);

        jPanel4.setOpaque(false);

        jLabel28.setText("Quality");

        fdrSlider1.setToolTipText("FDR Threshold");
        fdrSlider1.setOpaque(false);
        fdrSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fdrSlider1MouseReleased(evt);
            }
        });
        fdrSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                fdrSlider1MouseDragged(evt);
            }
        });

        jLabel29.setText("Quantity");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fdrSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel29)
                    .addComponent(fdrSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        frdFnrChartPanel.setOpaque(false);
        frdFnrChartPanel.setLayout(new javax.swing.BoxLayout(frdFnrChartPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout fdrFnrPanelLayout = new javax.swing.GroupLayout(fdrFnrPanel);
        fdrFnrPanel.setLayout(fdrFnrPanelLayout);
        fdrFnrPanelLayout.setHorizontalGroup(
            fdrFnrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fdrFnrPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(frdFnrChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        fdrFnrPanelLayout.setVerticalGroup(
            fdrFnrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fdrFnrPanelLayout.createSequentialGroup()
                .addComponent(frdFnrChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rightPlotSplitPane.setLeftComponent(fdrFnrPanel);

        benefitCostPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Benefit/Cost"));
        benefitCostPanel.setOpaque(false);

        jPanel5.setOpaque(false);

        jLabel31.setText("Quantity");

        fdrSlider2.setToolTipText("FDR Threshold");
        fdrSlider2.setOpaque(false);
        fdrSlider2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fdrSlider2MouseReleased(evt);
            }
        });
        fdrSlider2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                fdrSlider2MouseDragged(evt);
            }
        });

        jLabel32.setText("Quality");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fdrSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel32)
                    .addComponent(fdrSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        benefitCostChartPanel.setOpaque(false);
        benefitCostChartPanel.setLayout(new javax.swing.BoxLayout(benefitCostChartPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout benefitCostPanelLayout = new javax.swing.GroupLayout(benefitCostPanel);
        benefitCostPanel.setLayout(benefitCostPanelLayout);
        benefitCostPanelLayout.setHorizontalGroup(
            benefitCostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(benefitCostPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(benefitCostChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        benefitCostPanelLayout.setVerticalGroup(
            benefitCostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, benefitCostPanelLayout.createSequentialGroup()
                .addComponent(benefitCostChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rightPlotSplitPane.setRightComponent(benefitCostPanel);

        leftPlotSplitPane.setRightComponent(rightPlotSplitPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(leftPlotSplitPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1185, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leftPlotSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void groupListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupListMousePressed
        groupSelectionChanged();
    }//GEN-LAST:event_groupListMousePressed

    private void confidenceClassicalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confidenceClassicalTxtActionPerformed
        try {
            lastThreshold = new Double(confidenceClassicalTxt.getText());
            lastThresholdType = 0;
            updateResults();
            updateDisplayedComponents();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please verify the given threshold.", "Import error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_confidenceClassicalTxtActionPerformed

    private void fdrClassicalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdrClassicalTxtActionPerformed
        try {
            lastThreshold = new Double(fdrClassicalTxt.getText());
            lastThresholdType = 1;
            updateResults();
            updateDisplayedComponents();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please verify the given threshold.", "Import error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_fdrClassicalTxtActionPerformed

    private void fnrClassicalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnrClassicalTxtActionPerformed
        try {
            lastThreshold = new Double(fnrClassicalTxt.getText());
            lastThresholdType = 2;
            updateResults();
            updateDisplayedComponents();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please verify the given threshold.", "Import error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_fnrClassicalTxtActionPerformed

    private void fdrCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdrCombo1ActionPerformed
        TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();
        if (fdrCombo1.getSelectedIndex() == 0) {
            currentResults.setClassicalEstimators(true);
        } else {
            currentResults.setClassicalEstimators(false);
        }
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        updateResults();
        updateDisplayedComponents();
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_fdrCombo1ActionPerformed

    private void confidenceSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confidenceSliderMouseReleased
        lastThreshold = new Double(confidenceSlider.getValue());
        lastThresholdType = 0;
        updateResults();
        updateDisplayedComponents();
    }//GEN-LAST:event_confidenceSliderMouseReleased

    private void confidenceSliderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confidenceSliderMousePressed
    }//GEN-LAST:event_confidenceSliderMousePressed

    private void confidenceSliderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confidenceSliderMouseExited
    }//GEN-LAST:event_confidenceSliderMouseExited

    private void confidenceSliderMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confidenceSliderMouseMoved
    }//GEN-LAST:event_confidenceSliderMouseMoved

    private void confidenceSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confidenceSliderMouseDragged
        confidenceClassicalTxt.setText(confidenceSlider.getValue() + "");
    }//GEN-LAST:event_confidenceSliderMouseDragged

    private void fdrSlider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fdrSlider1MouseDragged
        fdrClassicalTxt.setText(fdrSlider1.getValue() + "");
    }//GEN-LAST:event_fdrSlider1MouseDragged

    private void fdrSlider2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fdrSlider2MouseDragged
        fdrClassicalTxt.setText(fdrSlider2.getValue() + "");
    }//GEN-LAST:event_fdrSlider2MouseDragged

    private void fdrSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fdrSlider1MouseReleased
        lastThreshold = new Double(fdrSlider1.getValue());
        lastThresholdType = 1;
        fdrSlider2.setValue(fdrSlider1.getValue());
        updateResults();
        updateDisplayedComponents();
    }//GEN-LAST:event_fdrSlider1MouseReleased

    private void fdrSlider2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fdrSlider2MouseReleased
        lastThreshold = new Double(fdrSlider2.getValue());
        lastThresholdType = 1;
        fdrSlider1.setValue(fdrSlider2.getValue());
        updateResults();
        updateDisplayedComponents();
    }//GEN-LAST:event_fdrSlider2MouseReleased

    private void windowTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowTxtActionPerformed
        try {
            Integer newWindow = new Integer(windowTxt.getText());
            currentTargetDecoyMap.setWindowSize(newWindow);
            currentTargetDecoyMap.estimateProbabilities();
            targetDecoySeries = currentTargetDecoyMap.getTargetDecoySeries();
            updateResults();
            updateDisplayedComponents();
            modifiedMaps.put(groupList.getSelectedIndex(), true);
            applyButton.setEnabled(true);
            cancelButton.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please verify the given window size.", "Import error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_windowTxtActionPerformed

    private void sensitivitySliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sensitivitySliderMouseDragged
        Double newWindow = Math.pow(10, sensitivitySlider.getValue() / 50.0 - 1) * currentTargetDecoyMap.getnMax();
        windowTxt.setText(newWindow.intValue() + "");
    }//GEN-LAST:event_sensitivitySliderMouseDragged

    private void sensitivitySliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sensitivitySliderMouseReleased
        windowTxtActionPerformed(null);
    }//GEN-LAST:event_sensitivitySliderMouseReleased

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        if (groupList.getSelectedIndex() == 0) {
            applyProteins();
        } else if (peptideMap.keySet().contains(groupList.getSelectedIndex())) {
            recalculateProteins();
        } else {
            recalculatePeptidesAndProteins();
        }
        applyButton.setEnabled(false);
        cancelButton.setEnabled(false);
    }//GEN-LAST:event_applyButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        windowTxt.setText(currentTargetDecoyMap.getnMax() + "");
        windowTxtActionPerformed(null);
        applyButton.setEnabled(false);
        cancelButton.setEnabled(false);
        modifiedMaps.put(groupList.getSelectedIndex(), false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                leftPlotSplitPane.setDividerLocation(leftPlotSplitPane.getWidth() / 3);
                rightPlotSplitPane.setDividerLocation(rightPlotSplitPane.getWidth() / 2);
            }
        });
    }//GEN-LAST:event_formComponentResized

    private void groupListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_groupListKeyReleased
        groupSelectionChanged();
    }//GEN-LAST:event_groupListKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JPanel benefitCostChartPanel;
    private javax.swing.JPanel benefitCostPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField confidenceClassicalTxt;
    private javax.swing.JTextField confidenceProbaTxt;
    private javax.swing.JSlider confidenceSlider;
    private javax.swing.JTextField fdrClassicalTxt;
    private javax.swing.JComboBox fdrCombo1;
    private javax.swing.JPanel fdrFnrPanel;
    private javax.swing.JTextField fdrProbaTxt;
    private javax.swing.JSlider fdrSlider1;
    private javax.swing.JSlider fdrSlider2;
    private javax.swing.JTextField fnrClassicalTxt;
    private javax.swing.JTextField fnrProbaTxt;
    private javax.swing.JPanel frdFnrChartPanel;
    private javax.swing.JList groupList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSplitPane leftPlotSplitPane;
    private javax.swing.JTextField nFPClassicalTxt;
    private javax.swing.JTextField nFPProbaTxt;
    private javax.swing.JTextField nMaxTxt;
    private javax.swing.JTextField nTPClassicalTxt;
    private javax.swing.JTextField nTPProbaTxt;
    private javax.swing.JTextField nTotalTxt;
    private javax.swing.JTextField nValidatedClassicalTxt;
    private javax.swing.JTextField nValidatedProbaTxt;
    private javax.swing.JPanel pepChartPanel;
    private javax.swing.JPanel pepPanel;
    private javax.swing.JSplitPane rightPlotSplitPane;
    private javax.swing.JSlider sensitivitySlider;
    private javax.swing.JTextField windowTxt;
    // End of variables declaration//GEN-END:variables
    /**
     * the currently displayed Target Decoy map
     */
    private TargetDecoyMap currentTargetDecoyMap;
    /**
     * The Target Decoy metrics series of the currently displayed map
     */
    private TargetDecoySeries targetDecoySeries;
    /**
     * the psms map: # in the list -> map key
     */
    private HashMap<Integer, Integer> psmMap = new HashMap<Integer, Integer>();
    /**
     * The peptide map: # in the list -> map key
     */
    private HashMap<Integer, String> peptideMap = new HashMap<Integer, String>();
    /**
     * The PEP plot
     */
    private XYPlot pepPlot = new XYPlot();
    /**
     * The FDR/FNR plot
     */
    private XYPlot fdrPlot = new XYPlot();
    /**
     * The Benefit/cost plot
     */
    private XYPlot benefitCostPlot = new XYPlot();
    /**
     * The last threshold input
     */
    private double lastThreshold = 95;
    /**
     * The last threshold type
     * 0 -> confidence
     * 1 -> FDR
     * 2 -> FNR
     */
    private int lastThresholdType = 0;
    /**
     * The confidence threshold marker
     */
    private ValueMarker confidenceMarker = new ValueMarker(1);
    /**
     * Map keeping track of probabilities modifications
     */
    private HashMap<Integer, Boolean> modifiedMaps = new HashMap<Integer, Boolean>();
    /**
     * Metrics and methods used for posterior validation of PSMs and peptides
     */
    private PosteriorValidationMetrics posteriorValidationMetrics = new PosteriorValidationMetrics();
    /**
     * Boolean indicating that results are displayed
     */
    private boolean resultDisplayed = false;

    /**
     * This method displays results on the panel
     */
    public void displayResults() {
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        resultDisplayed = true;
        estimatePossibilities();

        PSMaps pSMaps = new PSMaps();
        pSMaps = (PSMaps) peptideShakerGUI.getIdentification().getUrParam(pSMaps);
        ArrayList<String> peptideKeys = pSMaps.getPeptideSpecificMap().getKeys();
        HashMap<Integer, String> psmKeys = pSMaps.getPsmSpecificMap().getKeys();

        int nMaps = 3 + peptideKeys.size() + psmKeys.size();
        String[] listContent = new String[nMaps];
        listContent[0] = "Proteins";
        modifiedMaps.put(0, false);
        listContent[1] = "Peptides";
        int cpt = 2;
        for (String pepitdeKey : peptideKeys) {
            peptideMap.put(cpt, pepitdeKey);
            listContent[cpt] = "    " + pepitdeKey;
            modifiedMaps.put(cpt, false);
            cpt++;
        }
        listContent[cpt] = "PSMs";
        cpt++;
        for (Integer psmKey : psmKeys.keySet()) {
            psmMap.put(cpt, psmKey);
            listContent[cpt] = "    " + psmKeys.get(psmKey);
            modifiedMaps.put(cpt, false);
            cpt++;
        }
        groupList.setListData(listContent);
        groupList.setSelectedIndex(0);

        groupSelectionChanged();
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    /**
     * Method called whenever a new group selection occurred
     */
    private void groupSelectionChanged() {
        PSMaps pSMaps = new PSMaps();
        pSMaps = (PSMaps) peptideShakerGUI.getIdentification().getUrParam(pSMaps);
        int selectedGroup = groupList.getSelectedIndex();
        if (selectedGroup == 0) {
            currentTargetDecoyMap = pSMaps.getProteinMap().getTargetDecoyMap();
            boolean found = false;
            for (int key : psmMap.keySet()) {
                if (modifiedMaps.get(key)) {
                    found = true;
                    break;
                }
            }
            if (found) {
                int outcome = JOptionPane.showConfirmDialog(this,
                        "Probabilities modifications at the PSM level will influence protein results.\n"
                        + "Recalculate probabilities?", "Non Applied Changes", JOptionPane.YES_NO_OPTION);
                if (outcome == JOptionPane.YES_OPTION) {
                    recalculatePeptidesAndProteins();
                }
            } else {
                for (int key : peptideMap.keySet()) {
                    if (modifiedMaps.get(key)) {
                        found = true;
                        break;
                    }
                }
                if (found) {
                    int outcome = JOptionPane.showConfirmDialog(this,
                            "Probabilities modifications at the peptide level will influence protein results.\n"
                            + "Recalculate probabilities?", "Non Applied Changes", JOptionPane.YES_NO_OPTION);
                    if (outcome == JOptionPane.YES_OPTION) {
                        recalculateProteins();
                    }
                }
            }
        } else if (peptideMap.containsKey(selectedGroup)) {
            currentTargetDecoyMap = pSMaps.getPeptideSpecificMap().getTargetDecoyMap(peptideMap.get(selectedGroup));
            boolean found = false;
            for (int key : psmMap.keySet()) {
                if (modifiedMaps.get(key)) {
                    found = true;
                    break;
                }
            }
            if (found) {
                int outcome = JOptionPane.showConfirmDialog(this, 
                        "Probabilities modifications at the PSM level will influence peptide results.\n"
                        + "Recalculate probabilities?", "Non Applied Changes", JOptionPane.YES_NO_OPTION);
                if (outcome == JOptionPane.YES_OPTION) {
                    recalculatePeptidesAndProteins();
                }
            }
        } else if (psmMap.containsKey(selectedGroup)) {
            currentTargetDecoyMap = pSMaps.getPsmSpecificMap().getTargetDecoyMap(psmMap.get(selectedGroup));
        } else if (selectedGroup == peptideMap.size()) {
            clearScreen();
            int peptideSpaceSize = 0;
            double nTPTotal = 0;
            for (String peptideSelection : peptideMap.values()) {
                currentTargetDecoyMap = pSMaps.getPeptideSpecificMap().getTargetDecoyMap(peptideSelection);
                TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();
                if (currentResults.getConfidenceLimit() == -1) {
                    currentResults.setConfidenceLimit(95);
                    currentTargetDecoyMap.getTargetDecoySeries().getConfidenceResults(currentResults);
                }
                double proteinScore = pSMaps.getProteinMap().getTargetDecoyMap().getTargetDecoyResults().getScoreLimit();
                PosteriorValidationPoint posteriorValidationPoint = posteriorValidationMetrics.getResults(proteinScore);
                peptideSpaceSize = posteriorValidationPoint.peptideSpaceSize;
                nTPTotal += currentResults.getnTPTotal();
            }
            BigDecimal p = BigDecimal.ONE;
            p = p.divide(new BigDecimal(posteriorValidationMetrics.getSearchSpace()), BigDecimal.ROUND_HALF_DOWN);
            BigDecimal nFP = new BigDecimal(peptideSpaceSize);
            nFP = nFP.multiply(p);
            BigDecimal nTP = new BigDecimal(peptideSpaceSize);
            nTP = nTP.subtract(nFP);
            BigDecimal fdr = nFP.divide(new BigDecimal(peptideSpaceSize));

            nTotalTxt.setText(Util.roundDouble(nTPTotal, 2) + "");
            nValidatedProbaTxt.setEnabled(true);
            nFPProbaTxt.setEnabled(true);
            nTPProbaTxt.setEnabled(true);
            confidenceProbaTxt.setEnabled(true);
            fdrProbaTxt.setEnabled(true);
            fnrProbaTxt.setEnabled(true);
            nValidatedProbaTxt.setText(Util.roundDouble(peptideSpaceSize, 2) + "");
            nFPProbaTxt.setText(Util.roundDouble(nFP.doubleValue(), 2) + "");
            nTPProbaTxt.setText(Util.roundDouble(nTP.doubleValue(), 2) + "");
            confidenceProbaTxt.setText(p.toEngineeringString());
            fdrProbaTxt.setText(Util.roundDouble(fdr.doubleValue(), 2) + "");

            try {
                BigDecimal fnr = new BigDecimal(nTPTotal);
                fnr = fnr.subtract(nTP);
                fnr = fnr.divide(new BigDecimal(nTPTotal), BigDecimal.ROUND_HALF_DOWN);
                fnr = fnr.multiply(new BigDecimal(100));
                fnrProbaTxt.setText(Util.roundDouble(fnr.doubleValue(), 2) + "");
            } catch (Exception e) {
                fnrProbaTxt.setText("");
            }

            applyButton.setEnabled(false);
            cancelButton.setEnabled(false);
            return;
        } else {
            clearScreen();
            int psmSpaceSize = 0;
            double nTPTotal = 0;

            for (int psmSelection : psmMap.values()) {
                currentTargetDecoyMap = pSMaps.getPsmSpecificMap().getTargetDecoyMap(psmSelection);
                TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();
                if (currentResults.getConfidenceLimit() == -1) {
                    currentResults.setConfidenceLimit(95);
                    currentTargetDecoyMap.getTargetDecoySeries().getConfidenceResults(currentResults);
                }
                double proteinScore = pSMaps.getProteinMap().getTargetDecoyMap().getTargetDecoyResults().getScoreLimit();
                PosteriorValidationPoint posteriorValidationPoint = posteriorValidationMetrics.getResults(proteinScore);
                psmSpaceSize = posteriorValidationPoint.psmSpaceSize;
                nTPTotal += currentResults.getnTPTotal();
            }

            BigDecimal p = BigDecimal.ONE;
            p = p.divide(new BigDecimal(posteriorValidationMetrics.getSearchSpace()), BigDecimal.ROUND_HALF_DOWN);
            BigDecimal nFP = new BigDecimal(psmSpaceSize);
            nFP = nFP.multiply(p);
            BigDecimal nTP = new BigDecimal(psmSpaceSize);
            nTP = nTP.subtract(nFP);
            BigDecimal fdr = nFP.divide(new BigDecimal(psmSpaceSize));

            nTotalTxt.setText(Util.roundDouble(nTPTotal, 2) + "");
            nValidatedProbaTxt.setEnabled(true);
            nFPProbaTxt.setEnabled(true);
            nTPProbaTxt.setEnabled(true);
            confidenceProbaTxt.setEnabled(true);
            fdrProbaTxt.setEnabled(true);
            fnrProbaTxt.setEnabled(true);
            nValidatedProbaTxt.setText(Util.roundDouble(psmSpaceSize, 2) + "");
            nFPProbaTxt.setText(Util.roundDouble(nFP.doubleValue(), 2) + "");
            nTPProbaTxt.setText(Util.roundDouble(nTP.doubleValue(), 2) + "");
            confidenceProbaTxt.setText(p.toEngineeringString());
            fdrProbaTxt.setText(Util.roundDouble(fdr.doubleValue(), 2) + "");

            try {
                BigDecimal fnr = new BigDecimal(nTPTotal);
                fnr = fnr.subtract(nTP);
                fnr = fnr.divide(new BigDecimal(nTPTotal), BigDecimal.ROUND_HALF_DOWN);
                fnr = fnr.multiply(new BigDecimal(100));
                fnrProbaTxt.setText(Util.roundDouble(fnr.doubleValue(), 2) + "");
            } catch (Exception e) {
                fnrProbaTxt.setText("");
            }

            applyButton.setEnabled(false);
            cancelButton.setEnabled(false);
            return;
        }

        applyButton.setEnabled(modifiedMaps.get(groupList.getSelectedIndex()));
        cancelButton.setEnabled(modifiedMaps.get(groupList.getSelectedIndex()));
        nMaxTxt.setText(currentTargetDecoyMap.getnMax() + "");
        targetDecoySeries = currentTargetDecoyMap.getTargetDecoySeries();
        TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();

        if (currentResults.getConfidenceLimit() == -1) {

            if (currentTargetDecoyMap.suspiciousInput()) {
                currentResults.setClassicalEstimators(true);
            } else {
                currentResults.setClassicalEstimators(false);
            }

            currentResults.setClassicalValidation(true);
            currentResults.setConfidenceLimit(lastThreshold);
            targetDecoySeries.getConfidenceResults(currentResults);

            if (groupList.getSelectedIndex() == 0) {
                // @TODO: do something here??
            } else {
                currentResults.setClassicalValidation(false);
            }
        }

        updateDisplayedComponents();
    }

    /**
     * Updates the displayed results whenever a new threshold is given
     */
    private void updateResults() {

        TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();

        if (lastThresholdType == 0) {
            currentResults.setConfidenceLimit(lastThreshold);
            targetDecoySeries.getConfidenceResults(currentResults);
        } else if (lastThresholdType == 1) {
            currentResults.setFdrLimit(lastThreshold);
            targetDecoySeries.getFDRResults(currentResults);
        } else if (lastThresholdType == 2) {
            currentResults.setFnrLimit(lastThreshold);
            targetDecoySeries.getFNRResults(currentResults);
        }

        if (groupList.getSelectedIndex() == 0) {
            double proteinScore = currentResults.getScoreLimit();
            PosteriorValidationPoint posteriorValidationPoint = posteriorValidationMetrics.getResults(proteinScore);
            if (posteriorValidationPoint.peptideP1 > 0 || posteriorValidationPoint.psmP1 > 0) {
                JOptionPane.showConfirmDialog(this, "Some uptides/PSMs were validated with a PEP of 1.",
                        "Validation Alert", JOptionPane.OK_OPTION, JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    /**
     * Updates the updates the different components of the gui with the new results.
     * 
     * @param map boolean indicating whether a map is present
     */
    private void updateDisplayedComponents() {

        TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();
        nTotalTxt.setText(Util.roundDouble(currentResults.getnTPTotal(), 2) + "");
        nValidatedClassicalTxt.setText(Util.roundDouble(currentResults.getN(), 2) + "");
        nFPClassicalTxt.setText(Util.roundDouble(currentResults.getnFP(), 2) + "");
        nTPClassicalTxt.setText(Util.roundDouble(currentResults.getnTP(), 2) + "");
        confidenceClassicalTxt.setText(Util.roundDouble(currentResults.getConfidenceLimit(), 2) + "");
        fdrClassicalTxt.setText(Util.roundDouble(currentResults.getFdrLimit(), 2) + "");
        fnrClassicalTxt.setText(Util.roundDouble(currentResults.getFnrLimit(), 2) + "");
        confidenceSlider.setValue(currentResults.getConfidenceLimit().intValue());
        fdrSlider1.setValue(currentResults.getFdrLimit().intValue());
        fdrSlider2.setValue(currentResults.getFdrLimit().intValue());
        windowTxt.setText(currentTargetDecoyMap.getWindowSize() + "");
        Double newPosition = 50 * (Math.log10(currentTargetDecoyMap.getWindowSize() / (double) currentTargetDecoyMap.getnMax()) + 1);
        sensitivitySlider.setValue(newPosition.intValue());

        PSMaps pSMaps = new PSMaps();
        pSMaps = (PSMaps) peptideShakerGUI.getIdentification().getUrParam(pSMaps);
        double proteinScore = pSMaps.getProteinMap().getTargetDecoyMap().getTargetDecoyResults().getScoreLimit();
        PosteriorValidationPoint posteriorValidationPoint = posteriorValidationMetrics.getResults(proteinScore);
        BigDecimal p = BigDecimal.ONE;
        p = p.divide(new BigDecimal(posteriorValidationMetrics.getSearchSpace()), BigDecimal.ROUND_HALF_DOWN);

        if (groupList.getSelectedIndex() == 0) {
            //probaValidationCheck.setEnabled(false);
            nValidatedProbaTxt.setEnabled(false);
            nFPProbaTxt.setEnabled(false);
            nTPProbaTxt.setEnabled(false);
            confidenceProbaTxt.setEnabled(false);
            fdrProbaTxt.setEnabled(false);
            fnrProbaTxt.setEnabled(false);
            nValidatedProbaTxt.setText("");
            nFPProbaTxt.setText("");
            nTPProbaTxt.setText("");
            confidenceProbaTxt.setText("");
            fdrProbaTxt.setText("");
            fnrProbaTxt.setText("");
        } else if (peptideMap.containsKey(groupList.getSelectedIndex())) {
            String peptideKey = peptideMap.get(groupList.getSelectedIndex());
            BigDecimal nFP = new BigDecimal(posteriorValidationPoint.specificPeptideSpaceSize.get(peptideKey));
            nFP = nFP.multiply(p);
            BigDecimal nTP = new BigDecimal(posteriorValidationPoint.specificPeptideSpaceSize.get(peptideKey));
            nTP = nTP.subtract(nFP);
            BigDecimal fdr = nFP.divide(new BigDecimal(posteriorValidationPoint.specificPeptideSpaceSize.get(peptideKey)));

            nValidatedProbaTxt.setEnabled(true);
            nFPProbaTxt.setEnabled(true);
            nTPProbaTxt.setEnabled(true);
            confidenceProbaTxt.setEnabled(true);
            fdrProbaTxt.setEnabled(true);
            fnrProbaTxt.setEnabled(true);
            nValidatedProbaTxt.setText(posteriorValidationPoint.specificPeptideSpaceSize.get(peptideKey) + "");
            nFPProbaTxt.setText(nFP + "");
            nTPProbaTxt.setText(nTP + "");
            confidenceProbaTxt.setText(p.toEngineeringString());
            fdrProbaTxt.setText(fdr + "");

            try {
                BigDecimal fnr = new BigDecimal(currentResults.getnTPTotal());
                fnr = fnr.subtract(nTP);
                fnr = fnr.divide(new BigDecimal(currentResults.getnTPTotal()), BigDecimal.ROUND_HALF_DOWN);
                fnr = fnr.multiply(new BigDecimal(100));
                fnrProbaTxt.setText(Util.roundDouble(fnr.doubleValue(), 2) + "");
            } catch (Exception e) {
                fnrProbaTxt.setText("");
            }

        } else if (psmMap.containsKey(groupList.getSelectedIndex())) {

            int psmKey = psmMap.get(groupList.getSelectedIndex());
            BigDecimal nFP = new BigDecimal(posteriorValidationPoint.specificPsmSpaceSize.get(psmKey));
            nFP = nFP.multiply(p);
            BigDecimal nTP = new BigDecimal(posteriorValidationPoint.specificPsmSpaceSize.get(psmKey));
            nTP = nTP.subtract(nFP);
            BigDecimal fdr = nFP.divide(new BigDecimal(posteriorValidationPoint.specificPsmSpaceSize.get(psmKey)));

            nValidatedProbaTxt.setEnabled(true);
            nFPProbaTxt.setEnabled(true);
            nTPProbaTxt.setEnabled(true);
            confidenceProbaTxt.setEnabled(true);
            fdrProbaTxt.setEnabled(true);
            fnrProbaTxt.setEnabled(true);
            nValidatedProbaTxt.setText(posteriorValidationPoint.specificPsmSpaceSize.get(psmKey) + "");
            nFPProbaTxt.setText(nFP + "");
            nTPProbaTxt.setText(nTP + "");
            confidenceProbaTxt.setText(p + "");
            fdrProbaTxt.setText(fdr + "");

            try {
                BigDecimal fnr = new BigDecimal(currentResults.getnTPTotal());
                fnr = fnr.subtract(nTP);
                fnr = fnr.divide(new BigDecimal(currentResults.getnTPTotal()), BigDecimal.ROUND_HALF_DOWN);
                fnr = fnr.multiply(new BigDecimal(100));
                fnrProbaTxt.setText(Util.roundDouble(fnr.doubleValue(), 2) + "");
            } catch (Exception e) {
                fnrProbaTxt.setText("");
            }

        } else {
            nValidatedProbaTxt.setEnabled(true);
            nFPProbaTxt.setEnabled(true);
            nTPProbaTxt.setEnabled(true);
            confidenceProbaTxt.setEnabled(true);
            fdrProbaTxt.setEnabled(true);
            fnrProbaTxt.setEnabled(true);
            nValidatedProbaTxt.setText("");
            nFPProbaTxt.setText("");
            nTPProbaTxt.setText("");
            confidenceProbaTxt.setText("");
            fdrProbaTxt.setText("");
            fnrProbaTxt.setText("");
        }

        if (currentResults.isClassicalEstimators()) {
            nTotalTxt.setEnabled(false);
            fnrClassicalTxt.setEnabled(false);
            fdrCombo1.setSelectedIndex(0);
        } else {
            nTotalTxt.setEnabled(true);
            fnrClassicalTxt.setEnabled(true);
            fdrCombo1.setSelectedIndex(1);
        }

        if (currentResults.isClassicalValidation()) {
            confidenceSlider.setEnabled(true);
            fdrSlider1.setEnabled(true);
            fdrSlider2.setEnabled(true);
        } else {
            confidenceSlider.setEnabled(false);
            fdrSlider1.setEnabled(false);
            fdrSlider2.setEnabled(false);
        }
        updateCharts();
    }

    /**
     * Updates the statistical charts
     */
    private void updateCharts() {
        updatePepChart();
        updateFDRChart();
        updateCostBenefitChart();
        setMarkers();
        pepPanel.revalidate();
        pepPanel.repaint();
        fdrFnrPanel.revalidate();
        fdrFnrPanel.repaint();
        benefitCostChartPanel.revalidate();
        benefitCostChartPanel.repaint();
    }

    /**
     * Sets the threshold marker
     */
    private void setMarkers() {

        TargetDecoyResults currentResults = currentTargetDecoyMap.getTargetDecoyResults();

        confidenceMarker.setValue(currentResults.getScoreLimit());

        double[] score = {currentResults.getScoreLimit()};
        double[] fdr = {currentResults.getFdrLimit()};
        double[] fnr = {currentResults.getFnrLimit()};
        double[] benefit = {100 - currentResults.getFnrLimit()};

        DefaultXYDataset fdrData = new DefaultXYDataset();
        double[][] fdrSeries = {score, fdr};
        fdrData.addSeries("Retained FDR ", fdrSeries);
        fdrPlot.setDataset(3, fdrData);
        fdrPlot.mapDatasetToRangeAxis(3, 0);

        DefaultXYDataset probaFnrData = new DefaultXYDataset();
        double[][] probaFnrSeries = {score, fnr};
        probaFnrData.addSeries("Retained FNR ", probaFnrSeries);
        fdrPlot.setDataset(4, probaFnrData);
        fdrPlot.mapDatasetToRangeAxis(4, 0);

        XYLineAndShapeRenderer fdrRendrer = new XYLineAndShapeRenderer();
        fdrRendrer.setSeriesShapesVisible(0, true);
        fdrRendrer.setSeriesLinesVisible(0, false);
        fdrRendrer.setSeriesShape(0, DefaultDrawingSupplier.createStandardSeriesShapes()[1]);
        if (currentResults.isClassicalEstimators()) {
            fdrRendrer.setSeriesPaint(0, Color.blue);
        } else {
            fdrRendrer.setSeriesPaint(0, Color.green);
        }
        fdrPlot.setRenderer(3, fdrRendrer);

        XYLineAndShapeRenderer probaFnrRendrer = new XYLineAndShapeRenderer();
        probaFnrRendrer.setSeriesShapesVisible(0, true);
        probaFnrRendrer.setSeriesLinesVisible(0, false);
        probaFnrRendrer.setSeriesPaint(0, Color.RED);
        probaFnrRendrer.setSeriesShape(0, DefaultDrawingSupplier.createStandardSeriesShapes()[2]);
        fdrPlot.setRenderer(4, probaFnrRendrer);


        DefaultXYDataset benefitData = new DefaultXYDataset();
        double[][] benefitSeries = {fdr, benefit};
        benefitData.addSeries("Retained Benefit/Cost", benefitSeries);
        benefitCostPlot.setDataset(1, benefitData);
        benefitCostPlot.mapDatasetToRangeAxis(1, 0);

        XYLineAndShapeRenderer benefitRendrer = new XYLineAndShapeRenderer();
        benefitRendrer.setSeriesShapesVisible(0, true);
        benefitRendrer.setSeriesLinesVisible(0, false);
        benefitRendrer.setSeriesPaint(0, Color.blue);
        benefitRendrer.setSeriesShape(0, DefaultDrawingSupplier.createStandardSeriesShapes()[1]);
        benefitCostPlot.setRenderer(1, benefitRendrer);
    }

    /**
     * Updates the pep chart
     */
    private void updatePepChart() {

        DefaultXYDataset pepData = new DefaultXYDataset();
        double[][] pepSeries = {targetDecoySeries.getScores(), targetDecoySeries.getConfidence()};
        pepData.addSeries("Confidence", pepSeries);
        pepPlot.setDataset(0, pepData);
        pepPlot.mapDatasetToRangeAxis(0, 0);

        XYLineAndShapeRenderer pepRendrer = new XYLineAndShapeRenderer();
        pepRendrer.setSeriesShapesVisible(0, false);
        pepRendrer.setSeriesLinesVisible(0, true);
        pepRendrer.setSeriesPaint(0, Color.blue);
        pepRendrer.setSeriesStroke(0, new BasicStroke(LINE_WIDTH));
        pepPlot.setRenderer(0, pepRendrer);

        JFreeChart pepChart = new JFreeChart(pepPlot);
        ChartPanel chartPanel = new ChartPanel(pepChart);

        // set background color
        pepChart.getPlot().setBackgroundPaint(Color.WHITE);
        pepChart.setBackgroundPaint(Color.WHITE);
        chartPanel.setBackground(Color.WHITE);

        pepChartPanel.removeAll();
        pepChartPanel.add(chartPanel);
        pepChartPanel.revalidate();
        pepChartPanel.repaint();
    }

    /**
     * Updates the FDR chart
     */
    private void updateFDRChart() {
        DefaultXYDataset classicalFdrData = new DefaultXYDataset();
        double[][] classicalFdrSeries = {targetDecoySeries.getScores(), targetDecoySeries.getClassicalFDR()};
        classicalFdrData.addSeries("Classical FDR ", classicalFdrSeries);
        fdrPlot.setDataset(0, classicalFdrData);
        fdrPlot.mapDatasetToRangeAxis(0, 0);

        DefaultXYDataset probaFdrData = new DefaultXYDataset();
        double[][] probaFdrSeries = {targetDecoySeries.getScores(), targetDecoySeries.getProbaFDR()};
        probaFdrData.addSeries("Probabilistic FDR ", probaFdrSeries);
        fdrPlot.setDataset(1, probaFdrData);
        fdrPlot.mapDatasetToRangeAxis(1, 0);

        DefaultXYDataset probaFnrData = new DefaultXYDataset();
        double[][] probaFnrSeries = {targetDecoySeries.getScores(), targetDecoySeries.getProbaFNR()};
        probaFnrData.addSeries("Probabilistic FNR ", probaFnrSeries);
        fdrPlot.setDataset(2, probaFnrData);
        fdrPlot.mapDatasetToRangeAxis(2, 0);

        XYLineAndShapeRenderer classicalFdrRendrer = new XYLineAndShapeRenderer();
        classicalFdrRendrer.setSeriesShapesVisible(0, false);
        classicalFdrRendrer.setSeriesLinesVisible(0, true);
        classicalFdrRendrer.setSeriesPaint(0, Color.blue);
        classicalFdrRendrer.setSeriesStroke(0, new BasicStroke(LINE_WIDTH));
        fdrPlot.setRenderer(0, classicalFdrRendrer);

        XYLineAndShapeRenderer probaFdrRendrer = new XYLineAndShapeRenderer();
        probaFdrRendrer.setSeriesShapesVisible(0, false);
        probaFdrRendrer.setSeriesLinesVisible(0, true);
        probaFdrRendrer.setSeriesPaint(0, Color.GREEN);
        probaFdrRendrer.setSeriesStroke(0, new BasicStroke(LINE_WIDTH));
        fdrPlot.setRenderer(1, probaFdrRendrer);

        XYLineAndShapeRenderer probaFnrRendrer = new XYLineAndShapeRenderer();
        probaFnrRendrer.setSeriesShapesVisible(0, false);
        probaFnrRendrer.setSeriesLinesVisible(0, true);
        probaFnrRendrer.setSeriesPaint(0, Color.RED);
        probaFnrRendrer.setSeriesStroke(0, new BasicStroke(LINE_WIDTH));
        fdrPlot.setRenderer(2, probaFnrRendrer);

        JFreeChart fdrChart = new JFreeChart(fdrPlot);
        ChartPanel chartPanel = new ChartPanel(fdrChart);

        // set background color
        fdrChart.getPlot().setBackgroundPaint(Color.WHITE);
        fdrChart.setBackgroundPaint(Color.WHITE);
        chartPanel.setBackground(Color.WHITE);

        frdFnrChartPanel.removeAll();
        frdFnrChartPanel.add(chartPanel);
        frdFnrChartPanel.revalidate();
        frdFnrChartPanel.repaint();
    }

    /**
     * Updates the cost benefit chart
     */
    private void updateCostBenefitChart() {
        DefaultXYDataset benefitData = new DefaultXYDataset();
        double[][] benefitSeries = {targetDecoySeries.getProbaFDR(), targetDecoySeries.getProbaBenefit()};
        benefitData.addSeries("Benefit", benefitSeries);
        benefitCostPlot.setDataset(0, benefitData);
        benefitCostPlot.mapDatasetToRangeAxis(0, 0);

        XYLineAndShapeRenderer benefitRendrer = new XYLineAndShapeRenderer();
        benefitRendrer.setSeriesShapesVisible(0, false);
        benefitRendrer.setSeriesLinesVisible(0, true);
        benefitRendrer.setSeriesPaint(0, Color.blue);
        benefitRendrer.setSeriesStroke(0, new BasicStroke(LINE_WIDTH));
        benefitCostPlot.setRenderer(0, benefitRendrer);

        JFreeChart benefitCostChart = new JFreeChart(benefitCostPlot);
        ChartPanel chartPanel = new ChartPanel(benefitCostChart);

        // set background color
        benefitCostChart.getPlot().setBackgroundPaint(Color.WHITE);
        benefitCostChart.setBackgroundPaint(Color.WHITE);
        chartPanel.setBackground(Color.WHITE);

        benefitCostChartPanel.removeAll();
        benefitCostChartPanel.add(chartPanel);
        benefitCostChartPanel.revalidate();
        benefitCostChartPanel.repaint();
    }

    /**
     * Removes the charts
     */
    private void clearCharts() {
        pepChartPanel.removeAll();
        pepChartPanel.revalidate();
        pepChartPanel.repaint();
        frdFnrChartPanel.removeAll();
        frdFnrChartPanel.revalidate();
        frdFnrChartPanel.repaint();
        benefitCostChartPanel.removeAll();
        benefitCostChartPanel.revalidate();
        benefitCostChartPanel.repaint();
    }

    /**
     * Clears the GUI
     */
    private void clearScreen() {
        nTotalTxt.setText("");
        nValidatedClassicalTxt.setText("");
        nFPClassicalTxt.setText("");
        nTPClassicalTxt.setText("");
        confidenceClassicalTxt.setText("");
        fdrClassicalTxt.setText("");
        fnrClassicalTxt.setText("");
        nValidatedProbaTxt.setText("");
        nFPProbaTxt.setText("");
        nTPProbaTxt.setText("");
        confidenceProbaTxt.setText("");
        fdrProbaTxt.setText("");
        fnrProbaTxt.setText("");
        nMaxTxt.setText("");
        clearCharts();
    }

    /**
     * Recalculates probabilities for peptides and proteins.
     */
    private void recalculatePeptidesAndProteins() {
        PSMaps pSMaps = new PSMaps();
        pSMaps = (PSMaps) peptideShakerGUI.getIdentification().getUrParam(pSMaps);
        PeptideShaker miniShaker = new PeptideShaker(peptideShakerGUI.getExperiment(), peptideShakerGUI.getSample(), peptideShakerGUI.getReplicateNumber(), pSMaps);
        try {
            miniShaker.spectrumMapChanged();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An identification conflict occured. If you can reproduce the error please contact the developers.", 
                    "Identification Conflict", JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
        }
        for (int key : modifiedMaps.keySet()) {
            modifiedMaps.put(key, false);
        }
    }

    /**
     * Recalculates probabilities for proteins only.
     */
    private void recalculateProteins() {
        PSMaps pSMaps = new PSMaps();
        pSMaps = (PSMaps) peptideShakerGUI.getIdentification().getUrParam(pSMaps);
        PeptideShaker miniShaker = new PeptideShaker(peptideShakerGUI.getExperiment(), peptideShakerGUI.getSample(), peptideShakerGUI.getReplicateNumber(), pSMaps);
        try {
            miniShaker.peptideMapChanged();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An identification conflict occured. If you can reproduce the error please contact the developers.", 
                    "Identification Conflict", JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
        }
        modifiedMaps.put(0, false);
        for (int key : peptideMap.keySet()) {
            modifiedMaps.put(key, false);
        }
    }

    /**
     * Apply the new protein settings.
     */
    private void applyProteins() {
        PSMaps pSMaps = new PSMaps();
        pSMaps = (PSMaps) peptideShakerGUI.getIdentification().getUrParam(pSMaps);
        PeptideShaker miniShaker = new PeptideShaker(peptideShakerGUI.getExperiment(), peptideShakerGUI.getSample(), peptideShakerGUI.getReplicateNumber(), pSMaps);
        miniShaker.proteinMapChanged();
        modifiedMaps.put(0, false);
    }

    /**
     * Estimates the database and dataset possibilities.
     */
    public void estimatePossibilities() {
        if (resultDisplayed) {
            PSMaps pSMaps = new PSMaps();
            pSMaps = (PSMaps) peptideShakerGUI.getIdentification().getUrParam(pSMaps);
            posteriorValidationMetrics.estimateDatasetPossibilities(peptideShakerGUI.getSearchParameters(),
                    peptideShakerGUI.getSequenceDataBase(), peptideShakerGUI.getIdentification(), pSMaps.getPeptideSpecificMap(), pSMaps.getPsmSpecificMap());
            posteriorValidationMetrics.estimateDataBasePossibilities(peptideShakerGUI.getSearchParameters(), peptideShakerGUI.getSequenceDataBase());
        }
    }
}
