package eu.isas.peptideshaker.gui;

import eu.isas.peptideshaker.filtering.PeptideFilter;
import eu.isas.peptideshaker.filtering.ProteinFilter;
import eu.isas.peptideshaker.filtering.PsmFilter;
import javax.swing.JOptionPane;

/**
 *
 * @author Marc Vaudel
 */
public class CreateFilterDialog extends javax.swing.JDialog {

    private PeptideShakerGUI peptideShakerGUI;
    private ProteinFilter proteinFilter;
    private PeptideFilter peptideFilter;
    private PsmFilter psmFilter;

    /** Creates new form CreateFilterDialog */
    public CreateFilterDialog(PeptideShakerGUI peptideShakerGUI, ProteinFilter proteinFilter, PeptideFilter peptideFilter, PsmFilter psmFilter) {
        super(peptideShakerGUI, true);
        this.peptideShakerGUI = peptideShakerGUI;
        initComponents();
        this.proteinFilter = proteinFilter;
        this.peptideFilter = peptideFilter;
        this.psmFilter = psmFilter;

        if (proteinFilter == null && peptideFilter == null) {
            jSplitPane1.setDividerLocation(0);
        } else if (proteinFilter == null) {
            jSplitPane1.setDividerLocation(0.25);
            jSplitPane3.setDividerLocation(0);
        } else if (peptideFilter == null) {
            jSplitPane1.setDividerLocation(0.25);
            jSplitPane3.setDividerLocation(1.0);
        } else {
            jSplitPane1.setDividerLocation(0.5);
            jSplitPane3.setDividerLocation(0.5);
        }
        if (psmFilter == null) {
            jSplitPane2.setDividerLocation(0);
        } else {
            jSplitPane2.setDividerLocation(0.5);
        }

        setLocationRelativeTo(peptideShakerGUI);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        psmFilterPane = new javax.swing.JPanel();
        psmEffectCmb = new javax.swing.JComboBox();
        psmFilterTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        psmFilterDescription = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        okPane = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        jSplitPane3 = new javax.swing.JSplitPane();
        proteinFilterPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        proteinFilterTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        proteinEffectCmb = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        proteinFilterDescription = new javax.swing.JTextField();
        peptideFilterPane = new javax.swing.JPanel();
        peptideEffectCmb = new javax.swing.JComboBox();
        peptideFilterTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        peptideFilterDescription = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(99, 83));

        jSplitPane2.setDividerLocation(100);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        psmEffectCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Star", "Hide" }));

        psmFilterTxt.setText("New filter");

        jLabel5.setText("PSM Filter Name:");

        jLabel6.setText("Effect:");

        jLabel9.setText("Description:");

        javax.swing.GroupLayout psmFilterPaneLayout = new javax.swing.GroupLayout(psmFilterPane);
        psmFilterPane.setLayout(psmFilterPaneLayout);
        psmFilterPaneLayout.setHorizontalGroup(
            psmFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psmFilterPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(psmFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(psmFilterPaneLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(psmFilterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, psmFilterPaneLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(psmEffectCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(psmFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(psmFilterPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                    .addComponent(psmFilterDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        psmFilterPaneLayout.setVerticalGroup(
            psmFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psmFilterPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(psmFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psmFilterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(psmFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psmEffectCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
            .addGroup(psmFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(psmFilterPaneLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addGroup(psmFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(psmFilterDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        jSplitPane2.setTopComponent(psmFilterPane);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout okPaneLayout = new javax.swing.GroupLayout(okPane);
        okPane.setLayout(okPaneLayout);
        okPaneLayout.setHorizontalGroup(
            okPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, okPaneLayout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        okPaneLayout.setVerticalGroup(
            okPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, okPaneLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(okPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        jSplitPane2.setRightComponent(okPane);

        jSplitPane1.setBottomComponent(jSplitPane2);

        jSplitPane3.setDividerLocation(100);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabel1.setText("Protein Fitler Name:");

        proteinFilterTxt.setText("New filter");

        jLabel2.setText("Effect:");

        proteinEffectCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Star", "Hide" }));

        jLabel7.setText("Description:");

        javax.swing.GroupLayout proteinFilterPaneLayout = new javax.swing.GroupLayout(proteinFilterPane);
        proteinFilterPane.setLayout(proteinFilterPaneLayout);
        proteinFilterPaneLayout.setHorizontalGroup(
            proteinFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proteinFilterPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(proteinFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(proteinFilterPaneLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(proteinEffectCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, proteinFilterPaneLayout.createSequentialGroup()
                        .addGroup(proteinFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(proteinFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(proteinFilterDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proteinFilterTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))))
                .addContainerGap())
        );
        proteinFilterPaneLayout.setVerticalGroup(
            proteinFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proteinFilterPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(proteinFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proteinFilterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(proteinFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(proteinFilterDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(proteinFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(proteinEffectCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSplitPane3.setTopComponent(proteinFilterPane);

        peptideEffectCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Star", "Hide" }));

        peptideFilterTxt.setText("New filter");

        jLabel3.setText("Peptide Filter Name:");

        jLabel4.setText("Effect:");

        jLabel8.setText("Description:");

        javax.swing.GroupLayout peptideFilterPaneLayout = new javax.swing.GroupLayout(peptideFilterPane);
        peptideFilterPane.setLayout(peptideFilterPaneLayout);
        peptideFilterPaneLayout.setHorizontalGroup(
            peptideFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peptideFilterPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(peptideFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(peptideFilterPaneLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(peptideFilterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peptideFilterPaneLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(peptideEffectCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(peptideFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(peptideFilterPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                    .addComponent(peptideFilterDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        peptideFilterPaneLayout.setVerticalGroup(
            peptideFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peptideFilterPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(peptideFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peptideFilterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(peptideFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peptideEffectCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
            .addGroup(peptideFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(peptideFilterPaneLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(peptideFilterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(peptideFilterDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(37, Short.MAX_VALUE)))
        );

        jSplitPane3.setRightComponent(peptideFilterPane);

        jSplitPane1.setLeftComponent(jSplitPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (proteinFilter != null) {
            String name = proteinFilterTxt.getText().trim();
            int outcome = JOptionPane.YES_OPTION;
            if (peptideShakerGUI.getFilterPreferences().filterExists(name)) {
                outcome = JOptionPane.showConfirmDialog(this,
                        "Should protein filter " + name + " be overwritten?", "Selected Filter Already Exists",
                        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            }
            if (outcome != JOptionPane.YES_OPTION) {
                return;
            }
            proteinFilter.setName(name);
            proteinFilter.setDescription(proteinFilterDescription.getText().trim());
            if (proteinEffectCmb.getSelectedIndex() == 0) {
                peptideShakerGUI.getFilterPreferences().addStarringFilter(proteinFilter);
            } else {
                peptideShakerGUI.getFilterPreferences().addHidingFilter(proteinFilter);
            }
        }
        if (peptideFilter != null) {
            String name = peptideFilterTxt.getText().trim();
            int outcome = JOptionPane.YES_OPTION;
            if (peptideShakerGUI.getFilterPreferences().filterExists(name)) {
                outcome = JOptionPane.showConfirmDialog(this,
                        "Should peptide filter " + name + " be overwritten?", "Selected Filter Already Exists",
                        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            }
            if (outcome != JOptionPane.YES_OPTION) {
                return;
            }
            peptideFilter.setName(name);
            peptideFilter.setDescription(peptideFilterDescription.getText().trim());
            if (peptideEffectCmb.getSelectedIndex() == 0) {
                peptideShakerGUI.getFilterPreferences().addStarringFilter(peptideFilter);
            } else {
                peptideShakerGUI.getFilterPreferences().addHidingFilter(peptideFilter);
            }
        }
        if (psmFilter != null) {
            String name = psmFilterTxt.getText().trim();
            int outcome = JOptionPane.YES_OPTION;
            if (peptideShakerGUI.getFilterPreferences().filterExists(name)) {
                outcome = JOptionPane.showConfirmDialog(this,
                        "Should PSM filter " + name + " be overwritten?", "Selected Filter Already Exists",
                        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            }
            if (outcome != JOptionPane.YES_OPTION) {
                return;
            }
            psmFilter.setName(name);
            psmFilter.setDescription(psmFilterDescription.getText().trim());
            if (psmEffectCmb.getSelectedIndex() == 0) {
                peptideShakerGUI.getFilterPreferences().addStarringFilter(psmFilter);
            } else {
                peptideShakerGUI.getFilterPreferences().addHidingFilter(psmFilter);
            }
        }
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel okPane;
    private javax.swing.JComboBox peptideEffectCmb;
    private javax.swing.JTextField peptideFilterDescription;
    private javax.swing.JPanel peptideFilterPane;
    private javax.swing.JTextField peptideFilterTxt;
    private javax.swing.JComboBox proteinEffectCmb;
    private javax.swing.JTextField proteinFilterDescription;
    private javax.swing.JPanel proteinFilterPane;
    private javax.swing.JTextField proteinFilterTxt;
    private javax.swing.JComboBox psmEffectCmb;
    private javax.swing.JTextField psmFilterDescription;
    private javax.swing.JPanel psmFilterPane;
    private javax.swing.JTextField psmFilterTxt;
    // End of variables declaration//GEN-END:variables
}
