package eu.isas.peptideshaker.gui.preferencesdialogs;

import com.compomics.util.gui.waiting.waitinghandlers.ProgressDialogX;
import eu.isas.peptideshaker.export.CsvExporter;
import eu.isas.peptideshaker.export.OutputGenerator;
import eu.isas.peptideshaker.gui.HelpDialog;
import eu.isas.peptideshaker.gui.PeptideShakerGUI;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 * Dialog for exporting protein, peptide, psms and search engine features.
 *
 * @author Marc Vaudel
 * @author Harald Barsnes
 */
public class FeaturesPreferencesDialog extends javax.swing.JDialog {

    /**
     * Peptide-Shaker main GUI.
     */
    private PeptideShakerGUI peptideShakerGUI;
    /**
     * The output generator will generate the output based on the user's choice.
     */
    private OutputGenerator outputGenerator;
    /**
     * A simple progress dialog.
     */
    private static ProgressDialogX progressDialog;

    /**
     * Creates a new ExportPreferencesDialog.
     *
     * @param peptideShakerGUI the PeptideShaker GUI parent
     */
    public FeaturesPreferencesDialog(PeptideShakerGUI peptideShakerGUI) {
        super(peptideShakerGUI, true);
        this.peptideShakerGUI = peptideShakerGUI;
        initComponents();
        this.outputGenerator = new OutputGenerator(peptideShakerGUI);
        this.pack();
        this.setLocationRelativeTo(peptideShakerGUI);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proteinScore1 = new javax.swing.JCheckBox();
        backgroundPanel = new javax.swing.JPanel();
        featuresPanel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        proteinsPanel = new javax.swing.JPanel();
        proteinAccession = new javax.swing.JCheckBox();
        proteinPI = new javax.swing.JCheckBox();
        proteinNPeptides = new javax.swing.JCheckBox();
        proteinNSpectra = new javax.swing.JCheckBox();
        proteinDescription = new javax.swing.JCheckBox();
        proteinEmpai = new javax.swing.JCheckBox();
        proteinNsaf = new javax.swing.JCheckBox();
        proteinScore = new javax.swing.JCheckBox();
        proteinConfidence = new javax.swing.JCheckBox();
        proteinExportAll = new javax.swing.JButton();
        proteinSequenceCoverage = new javax.swing.JCheckBox();
        ptmSummary = new javax.swing.JCheckBox();
        proteinValidated = new javax.swing.JCheckBox();
        proteinStarred = new javax.swing.JCheckBox();
        proteinHidden = new javax.swing.JCheckBox();
        proteinSelectAllLabel = new javax.swing.JLabel();
        proteinDeselectAllLabel = new javax.swing.JLabel();
        slashLabel1 = new javax.swing.JLabel();
        molecularWeight = new javax.swing.JCheckBox();
        peptidesPanel = new javax.swing.JPanel();
        peptideAccession = new javax.swing.JCheckBox();
        peptideModification = new javax.swing.JCheckBox();
        peptideNSpectra = new javax.swing.JCheckBox();
        peptideScore = new javax.swing.JCheckBox();
        peptideConfidence = new javax.swing.JCheckBox();
        peptideExportAll = new javax.swing.JButton();
        peptideSequence = new javax.swing.JCheckBox();
        peptidePosition = new javax.swing.JCheckBox();
        peptideLocation = new javax.swing.JCheckBox();
        peptideValidated = new javax.swing.JCheckBox();
        peptideStarred = new javax.swing.JCheckBox();
        peptideHidden = new javax.swing.JCheckBox();
        precursorCharges = new javax.swing.JCheckBox();
        peptideSurroundingAA = new javax.swing.JCheckBox();
        peptideUniqueOnly = new javax.swing.JCheckBox();
        proteinDescriptionPeptideTab = new javax.swing.JCheckBox();
        peptideSelectAllLabel = new javax.swing.JLabel();
        slashLabel2 = new javax.swing.JLabel();
        peptideDeselectAllLabel = new javax.swing.JLabel();
        psmPanel = new javax.swing.JPanel();
        psmAccession = new javax.swing.JCheckBox();
        psmSequence = new javax.swing.JCheckBox();
        psmFile = new javax.swing.JCheckBox();
        psmTitle = new javax.swing.JCheckBox();
        psmPrecursor = new javax.swing.JCheckBox();
        psmLocation = new javax.swing.JCheckBox();
        psmModification = new javax.swing.JCheckBox();
        psmScore = new javax.swing.JCheckBox();
        psmConfidence = new javax.swing.JCheckBox();
        psmExportAll = new javax.swing.JButton();
        psmValidated = new javax.swing.JCheckBox();
        psmStarred = new javax.swing.JCheckBox();
        psmHidden = new javax.swing.JCheckBox();
        proteinDescriptionPsmTab = new javax.swing.JCheckBox();
        psmSelectAllLabel = new javax.swing.JLabel();
        slashLabel3 = new javax.swing.JLabel();
        psmDeselectAllLabel = new javax.swing.JLabel();
        searchEnginePanel = new javax.swing.JPanel();
        assumptionAccession = new javax.swing.JCheckBox();
        assumptionSequence = new javax.swing.JCheckBox();
        assumptionModification = new javax.swing.JCheckBox();
        assumptionFile = new javax.swing.JCheckBox();
        assumptionTitle = new javax.swing.JCheckBox();
        assumptionPrecursor = new javax.swing.JCheckBox();
        assumptionScores = new javax.swing.JCheckBox();
        assumptionConfidence = new javax.swing.JCheckBox();
        assumptionExportAll = new javax.swing.JButton();
        assumptionValidated = new javax.swing.JCheckBox();
        proteinDescriptionSerarchEnginesTab = new javax.swing.JCheckBox();
        searchEnginesSelectAllLabel = new javax.swing.JLabel();
        slashLabel4 = new javax.swing.JLabel();
        searchEnginesDeselectAllLabel = new javax.swing.JLabel();
        projectPanel = new javax.swing.JPanel();
        exportAll = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        helpJButton = new javax.swing.JButton();

        proteinScore1.setText("Score");
        proteinScore1.setIconTextGap(10);
        proteinScore1.setOpaque(false);

        setTitle("Export Features");
        setResizable(false);

        backgroundPanel.setBackground(new java.awt.Color(230, 230, 230));

        featuresPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Features"));
        featuresPanel.setOpaque(false);

        proteinsPanel.setBackground(new java.awt.Color(230, 230, 230));

        proteinAccession.setSelected(true);
        proteinAccession.setText("Protein Accession");
        proteinAccession.setIconTextGap(10);
        proteinAccession.setOpaque(false);

        proteinPI.setText("Protein Inference");
        proteinPI.setIconTextGap(10);
        proteinPI.setOpaque(false);

        proteinNPeptides.setText("#Validated Peptides");
        proteinNPeptides.setIconTextGap(10);
        proteinNPeptides.setOpaque(false);

        proteinNSpectra.setText("#Validated Spectra");
        proteinNSpectra.setIconTextGap(10);
        proteinNSpectra.setOpaque(false);

        proteinDescription.setSelected(true);
        proteinDescription.setText("Protein Description");
        proteinDescription.setIconTextGap(10);
        proteinDescription.setOpaque(false);

        proteinEmpai.setText("emPAI");
        proteinEmpai.setIconTextGap(10);
        proteinEmpai.setOpaque(false);

        proteinNsaf.setText("NSAF");
        proteinNsaf.setIconTextGap(10);
        proteinNsaf.setOpaque(false);

        proteinScore.setText("Protein Score");
        proteinScore.setIconTextGap(10);
        proteinScore.setOpaque(false);

        proteinConfidence.setText("Protein Confidence");
        proteinConfidence.setIconTextGap(10);
        proteinConfidence.setOpaque(false);

        proteinExportAll.setText("Export");
        proteinExportAll.setToolTipText("Export selected protein details");
        proteinExportAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proteinExportAllActionPerformed(evt);
            }
        });

        proteinSequenceCoverage.setText("Sequence Coverage");
        proteinSequenceCoverage.setIconTextGap(10);
        proteinSequenceCoverage.setOpaque(false);

        ptmSummary.setText("PTM Summary");
        ptmSummary.setIconTextGap(10);
        ptmSummary.setOpaque(false);

        proteinValidated.setSelected(true);
        proteinValidated.setText("Request Validated");
        proteinValidated.setIconTextGap(10);
        proteinValidated.setOpaque(false);

        proteinStarred.setText("Request Starred");
        proteinStarred.setIconTextGap(10);
        proteinStarred.setOpaque(false);

        proteinHidden.setText("Include Hidden");
        proteinHidden.setIconTextGap(10);
        proteinHidden.setOpaque(false);

        proteinSelectAllLabel.setText("<html><a href>Select All<a></html>");
        proteinSelectAllLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proteinSelectAllLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                proteinSelectAllLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proteinSelectAllLabelMouseExited(evt);
            }
        });

        proteinDeselectAllLabel.setText("<html><a href>Deselect All<a></html>");
        proteinDeselectAllLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proteinDeselectAllLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                proteinDeselectAllLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proteinDeselectAllLabelMouseExited(evt);
            }
        });

        slashLabel1.setText("/");

        molecularWeight.setText("Molecular Weight");
        molecularWeight.setIconTextGap(10);
        molecularWeight.setOpaque(false);

        javax.swing.GroupLayout proteinsPanelLayout = new javax.swing.GroupLayout(proteinsPanel);
        proteinsPanel.setLayout(proteinsPanelLayout);
        proteinsPanelLayout.setHorizontalGroup(
            proteinsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proteinsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(proteinsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(proteinsPanelLayout.createSequentialGroup()
                        .addGroup(proteinsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proteinDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proteinAccession, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proteinScore, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proteinConfidence, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proteinNPeptides, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proteinPI, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(proteinsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(proteinNSpectra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(proteinSequenceCoverage, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(75, 75, 75)
                        .addGroup(proteinsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proteinNsaf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proteinEmpai, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proteinValidated, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proteinStarred, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proteinHidden, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptmSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(molecularWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(proteinsPanelLayout.createSequentialGroup()
                        .addComponent(proteinSelectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slashLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proteinDeselectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(proteinExportAll)))
                .addContainerGap())
        );

        proteinsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {proteinAccession, proteinConfidence, proteinDescription, proteinEmpai, proteinHidden, proteinNPeptides, proteinNSpectra, proteinNsaf, proteinPI, proteinScore, proteinSequenceCoverage, proteinStarred, proteinValidated, ptmSummary});

        proteinsPanelLayout.setVerticalGroup(
            proteinsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proteinsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(proteinsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(proteinsPanelLayout.createSequentialGroup()
                        .addComponent(proteinAccession)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proteinDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proteinPI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proteinScore))
                    .addGroup(proteinsPanelLayout.createSequentialGroup()
                        .addComponent(proteinEmpai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proteinNsaf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ptmSummary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(molecularWeight)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proteinConfidence)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(proteinsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(proteinsPanelLayout.createSequentialGroup()
                        .addComponent(proteinNPeptides)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proteinNSpectra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proteinSequenceCoverage))
                    .addGroup(proteinsPanelLayout.createSequentialGroup()
                        .addComponent(proteinValidated)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proteinStarred)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proteinHidden)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(proteinsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(proteinSelectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slashLabel1)
                    .addComponent(proteinDeselectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proteinExportAll))
                .addContainerGap())
        );

        proteinsPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {molecularWeight, proteinAccession, proteinConfidence, proteinDescription, proteinEmpai, proteinHidden, proteinNPeptides, proteinNSpectra, proteinNsaf, proteinPI, proteinScore, proteinSequenceCoverage, proteinStarred, proteinValidated, ptmSummary});

        tabbedPane.addTab("Proteins", proteinsPanel);

        peptidesPanel.setBackground(new java.awt.Color(230, 230, 230));

        peptideAccession.setSelected(true);
        peptideAccession.setText("Protein Accession");
        peptideAccession.setIconTextGap(10);
        peptideAccession.setOpaque(false);

        peptideModification.setText("Modification Status");
        peptideModification.setIconTextGap(10);
        peptideModification.setOpaque(false);

        peptideNSpectra.setText("#Validated Spectra");
        peptideNSpectra.setIconTextGap(10);
        peptideNSpectra.setOpaque(false);

        peptideScore.setText("Peptide Score");
        peptideScore.setIconTextGap(10);
        peptideScore.setOpaque(false);

        peptideConfidence.setSelected(true);
        peptideConfidence.setText("Peptide Confidence");
        peptideConfidence.setIconTextGap(10);
        peptideConfidence.setOpaque(false);

        peptideExportAll.setText("Export");
        peptideExportAll.setToolTipText("Export selected peptide details");
        peptideExportAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peptideExportAllActionPerformed(evt);
            }
        });

        peptideSequence.setSelected(true);
        peptideSequence.setText("Peptide Sequence");
        peptideSequence.setIconTextGap(10);
        peptideSequence.setOpaque(false);

        peptidePosition.setText("Peptide Position");
        peptidePosition.setIconTextGap(10);
        peptidePosition.setOpaque(false);

        peptideLocation.setText("Location Scores");
        peptideLocation.setIconTextGap(10);
        peptideLocation.setOpaque(false);

        peptideValidated.setSelected(true);
        peptideValidated.setText("Request Validated");
        peptideValidated.setIconTextGap(10);
        peptideValidated.setOpaque(false);

        peptideStarred.setText("Request Starred");
        peptideStarred.setIconTextGap(10);
        peptideStarred.setOpaque(false);

        peptideHidden.setText("Include Hidden");
        peptideHidden.setIconTextGap(10);
        peptideHidden.setOpaque(false);

        precursorCharges.setText("Precursor Charge(s)");
        precursorCharges.setIconTextGap(10);
        precursorCharges.setOpaque(false);

        peptideSurroundingAA.setText("Surrounding AA");
        peptideSurroundingAA.setIconTextGap(10);
        peptideSurroundingAA.setOpaque(false);

        peptideUniqueOnly.setText("Unique Only");
        peptideUniqueOnly.setIconTextGap(10);
        peptideUniqueOnly.setOpaque(false);

        proteinDescriptionPeptideTab.setSelected(true);
        proteinDescriptionPeptideTab.setText("Protein Description");
        proteinDescriptionPeptideTab.setIconTextGap(10);
        proteinDescriptionPeptideTab.setOpaque(false);

        peptideSelectAllLabel.setText("<html><a href>Select All<a></html>");
        peptideSelectAllLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peptideSelectAllLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                peptideSelectAllLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                peptideSelectAllLabelMouseExited(evt);
            }
        });

        slashLabel2.setText("/");

        peptideDeselectAllLabel.setText("<html><a href>Deselect All<a></html>");
        peptideDeselectAllLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peptideDeselectAllLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                peptideDeselectAllLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                peptideDeselectAllLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout peptidesPanelLayout = new javax.swing.GroupLayout(peptidesPanel);
        peptidesPanel.setLayout(peptidesPanelLayout);
        peptidesPanelLayout.setHorizontalGroup(
            peptidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peptidesPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(peptidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(peptidesPanelLayout.createSequentialGroup()
                        .addGroup(peptidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(peptidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(peptideAccession, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(peptideSequence, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(peptidePosition)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peptidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(peptideConfidence, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(peptideScore, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(peptideModification, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peptideLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proteinDescriptionPeptideTab, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(peptidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(peptideNSpectra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peptideUniqueOnly)
                            .addComponent(precursorCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peptideSurroundingAA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peptideValidated, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peptideHidden, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peptideStarred, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(peptidesPanelLayout.createSequentialGroup()
                        .addComponent(peptideSelectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slashLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peptideDeselectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(peptideExportAll)))
                .addContainerGap())
        );

        peptidesPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {peptideAccession, peptideConfidence, peptideHidden, peptideLocation, peptideModification, peptideNSpectra, peptidePosition, peptideScore, peptideSequence, peptideStarred, peptideSurroundingAA, peptideUniqueOnly, peptideValidated, precursorCharges});

        peptidesPanelLayout.setVerticalGroup(
            peptidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peptidesPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(peptidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(peptidesPanelLayout.createSequentialGroup()
                        .addComponent(peptideAccession)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proteinDescriptionPeptideTab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peptideSequence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peptidePosition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peptideScore))
                    .addGroup(peptidesPanelLayout.createSequentialGroup()
                        .addComponent(peptideNSpectra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precursorCharges)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peptideUniqueOnly)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peptideSurroundingAA, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(peptidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(peptidesPanelLayout.createSequentialGroup()
                        .addComponent(peptideValidated)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peptideStarred)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peptideHidden))
                    .addGroup(peptidesPanelLayout.createSequentialGroup()
                        .addComponent(peptideConfidence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peptideModification)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peptideLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(peptidesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(peptideSelectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slashLabel2)
                    .addComponent(peptideDeselectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peptideExportAll))
                .addContainerGap())
        );

        peptidesPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {peptideAccession, peptideConfidence, peptideHidden, peptideLocation, peptideModification, peptideNSpectra, peptidePosition, peptideScore, peptideSequence, peptideStarred, peptideSurroundingAA, peptideUniqueOnly, peptideValidated, precursorCharges});

        tabbedPane.addTab("Peptides", peptidesPanel);

        psmPanel.setBackground(new java.awt.Color(230, 230, 230));

        psmAccession.setSelected(true);
        psmAccession.setText("Protein Accession");
        psmAccession.setIconTextGap(10);
        psmAccession.setOpaque(false);

        psmSequence.setSelected(true);
        psmSequence.setText("Peptide Sequence");
        psmSequence.setIconTextGap(10);
        psmSequence.setOpaque(false);

        psmFile.setText("Spectrum File");
        psmFile.setIconTextGap(10);
        psmFile.setOpaque(false);

        psmTitle.setSelected(true);
        psmTitle.setText("Spectrum Title");
        psmTitle.setIconTextGap(10);
        psmTitle.setOpaque(false);

        psmPrecursor.setText("Precursor Details");
        psmPrecursor.setIconTextGap(10);
        psmPrecursor.setOpaque(false);

        psmLocation.setText("Location Scores");
        psmLocation.setIconTextGap(10);
        psmLocation.setOpaque(false);

        psmModification.setText("Modification Status");
        psmModification.setIconTextGap(10);
        psmModification.setOpaque(false);

        psmScore.setText("PSM Score");
        psmScore.setIconTextGap(10);
        psmScore.setOpaque(false);

        psmConfidence.setSelected(true);
        psmConfidence.setText("PSM Confidence");
        psmConfidence.setIconTextGap(10);
        psmConfidence.setOpaque(false);

        psmExportAll.setText("Export");
        psmExportAll.setToolTipText("Export selected PSM details");
        psmExportAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psmExportAllActionPerformed(evt);
            }
        });

        psmValidated.setSelected(true);
        psmValidated.setText("Request Validated");
        psmValidated.setIconTextGap(10);
        psmValidated.setOpaque(false);

        psmStarred.setText("Request Starred");
        psmStarred.setIconTextGap(10);
        psmStarred.setOpaque(false);

        psmHidden.setText("Include Hidden");
        psmHidden.setIconTextGap(10);
        psmHidden.setOpaque(false);

        proteinDescriptionPsmTab.setSelected(true);
        proteinDescriptionPsmTab.setText("Protein Description");
        proteinDescriptionPsmTab.setIconTextGap(10);
        proteinDescriptionPsmTab.setOpaque(false);

        psmSelectAllLabel.setText("<html><a href>Select All<a></html>");
        psmSelectAllLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psmSelectAllLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psmSelectAllLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psmSelectAllLabelMouseExited(evt);
            }
        });

        slashLabel3.setText("/");

        psmDeselectAllLabel.setText("<html><a href>Deselect All<a></html>");
        psmDeselectAllLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psmDeselectAllLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psmDeselectAllLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psmDeselectAllLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout psmPanelLayout = new javax.swing.GroupLayout(psmPanel);
        psmPanel.setLayout(psmPanelLayout);
        psmPanelLayout.setHorizontalGroup(
            psmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psmPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(psmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(psmPanelLayout.createSequentialGroup()
                        .addComponent(psmSequence, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(psmPanelLayout.createSequentialGroup()
                        .addGroup(psmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(psmPanelLayout.createSequentialGroup()
                                .addComponent(psmSelectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(slashLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(psmDeselectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(psmExportAll))
                            .addGroup(psmPanelLayout.createSequentialGroup()
                                .addGroup(psmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(psmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(psmLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(psmAccession, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(psmModification, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(psmPrecursor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(proteinDescriptionPsmTab, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, psmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(psmFile, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(psmTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(75, 75, 75)
                                .addGroup(psmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(psmHidden, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(psmStarred, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(psmConfidence, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(psmScore, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(psmValidated, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 8, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        psmPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {psmAccession, psmConfidence, psmFile, psmLocation, psmModification, psmPrecursor, psmScore, psmSequence, psmTitle});

        psmPanelLayout.setVerticalGroup(
            psmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psmPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(psmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(psmPanelLayout.createSequentialGroup()
                        .addComponent(psmScore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(psmConfidence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(psmValidated)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(psmStarred)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(psmHidden))
                    .addGroup(psmPanelLayout.createSequentialGroup()
                        .addComponent(psmAccession)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proteinDescriptionPsmTab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(psmSequence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(psmModification)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(psmLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(psmPrecursor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(psmFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(psmTitle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(psmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(psmSelectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slashLabel3)
                    .addComponent(psmDeselectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psmExportAll))
                .addContainerGap())
        );

        psmPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {psmAccession, psmConfidence, psmFile, psmLocation, psmModification, psmPrecursor, psmScore, psmSequence, psmTitle});

        tabbedPane.addTab("PSMs", psmPanel);

        searchEnginePanel.setBackground(new java.awt.Color(230, 230, 230));

        assumptionAccession.setSelected(true);
        assumptionAccession.setText("Protein Accession");
        assumptionAccession.setIconTextGap(10);
        assumptionAccession.setOpaque(false);

        assumptionSequence.setSelected(true);
        assumptionSequence.setText("Peptide Sequence");
        assumptionSequence.setIconTextGap(10);
        assumptionSequence.setOpaque(false);

        assumptionModification.setText("Modification Status");
        assumptionModification.setIconTextGap(10);
        assumptionModification.setOpaque(false);

        assumptionFile.setText("Spectrum File");
        assumptionFile.setIconTextGap(10);
        assumptionFile.setOpaque(false);

        assumptionTitle.setSelected(true);
        assumptionTitle.setText("Spectrum Title");
        assumptionTitle.setIconTextGap(10);
        assumptionTitle.setOpaque(false);

        assumptionPrecursor.setText("Precursor Details");
        assumptionPrecursor.setIconTextGap(10);
        assumptionPrecursor.setOpaque(false);

        assumptionScores.setSelected(true);
        assumptionScores.setText("Search Engine Scores");
        assumptionScores.setIconTextGap(10);
        assumptionScores.setOpaque(false);

        assumptionConfidence.setSelected(true);
        assumptionConfidence.setText("Confidence");
        assumptionConfidence.setIconTextGap(10);
        assumptionConfidence.setOpaque(false);

        assumptionExportAll.setText("Export");
        assumptionExportAll.setToolTipText("Export selected search engine details");
        assumptionExportAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assumptionExportAllActionPerformed(evt);
            }
        });

        assumptionValidated.setSelected(true);
        assumptionValidated.setText("Request Validated");
        assumptionValidated.setIconTextGap(10);
        assumptionValidated.setOpaque(false);

        proteinDescriptionSerarchEnginesTab.setSelected(true);
        proteinDescriptionSerarchEnginesTab.setText("Protein Description");
        proteinDescriptionSerarchEnginesTab.setIconTextGap(10);
        proteinDescriptionSerarchEnginesTab.setOpaque(false);

        searchEnginesSelectAllLabel.setText("<html><a href>Select All<a></html>");
        searchEnginesSelectAllLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchEnginesSelectAllLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchEnginesSelectAllLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchEnginesSelectAllLabelMouseExited(evt);
            }
        });

        slashLabel4.setText("/");

        searchEnginesDeselectAllLabel.setText("<html><a href>Deselect All<a></html>");
        searchEnginesDeselectAllLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchEnginesDeselectAllLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchEnginesDeselectAllLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchEnginesDeselectAllLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout searchEnginePanelLayout = new javax.swing.GroupLayout(searchEnginePanel);
        searchEnginePanel.setLayout(searchEnginePanelLayout);
        searchEnginePanelLayout.setHorizontalGroup(
            searchEnginePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchEnginePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(searchEnginePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchEnginePanelLayout.createSequentialGroup()
                        .addGroup(searchEnginePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assumptionScores, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assumptionConfidence, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(searchEnginePanelLayout.createSequentialGroup()
                        .addGroup(searchEnginePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchEnginePanelLayout.createSequentialGroup()
                                .addGroup(searchEnginePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(assumptionAccession, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(assumptionSequence, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(assumptionModification, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(assumptionFile, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(assumptionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(proteinDescriptionSerarchEnginesTab, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(searchEnginePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(assumptionValidated, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(assumptionPrecursor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 8, Short.MAX_VALUE))
                            .addGroup(searchEnginePanelLayout.createSequentialGroup()
                                .addComponent(searchEnginesSelectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(slashLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchEnginesDeselectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(assumptionExportAll)))
                        .addContainerGap())))
        );

        searchEnginePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {assumptionAccession, assumptionConfidence, assumptionFile, assumptionModification, assumptionPrecursor, assumptionSequence, assumptionTitle});

        searchEnginePanelLayout.setVerticalGroup(
            searchEnginePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchEnginePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(searchEnginePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assumptionAccession)
                    .addComponent(assumptionPrecursor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proteinDescriptionSerarchEnginesTab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assumptionSequence)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assumptionModification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assumptionFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchEnginePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assumptionTitle)
                    .addComponent(assumptionValidated))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assumptionScores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assumptionConfidence)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(searchEnginePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(searchEnginesSelectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slashLabel4)
                    .addComponent(searchEnginesDeselectAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assumptionExportAll))
                .addContainerGap())
        );

        searchEnginePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {assumptionAccession, assumptionConfidence, assumptionFile, assumptionModification, assumptionPrecursor, assumptionScores, assumptionSequence, assumptionTitle});

        tabbedPane.addTab("Search Engines", searchEnginePanel);

        projectPanel.setBackground(new java.awt.Color(230, 230, 230));

        exportAll.setText("Export All Identification Result");
        exportAll.setToolTipText("Export all the identification results as four tab separated text files.");
        exportAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportAllActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setText("Advanced export. For expert use only.");
        jLabel2.setToolTipText("Export all the identification results as four tab separated text files.");

        javax.swing.GroupLayout projectPanelLayout = new javax.swing.GroupLayout(projectPanel);
        projectPanel.setLayout(projectPanelLayout);
        projectPanelLayout.setHorizontalGroup(
            projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(exportAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        projectPanelLayout.setVerticalGroup(
            projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectPanelLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportAll)
                    .addComponent(jLabel2))
                .addGap(124, 124, 124))
        );

        tabbedPane.addTab("Project", projectPanel);

        javax.swing.GroupLayout featuresPanelLayout = new javax.swing.GroupLayout(featuresPanel);
        featuresPanel.setLayout(featuresPanelLayout);
        featuresPanelLayout.setHorizontalGroup(
            featuresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(featuresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );
        featuresPanelLayout.setVerticalGroup(
            featuresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(featuresPanelLayout.createSequentialGroup()
                .addComponent(tabbedPane)
                .addContainerGap())
        );

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        helpJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/help.GIF"))); // NOI18N
        helpJButton.setToolTipText("Help");
        helpJButton.setBorder(null);
        helpJButton.setBorderPainted(false);
        helpJButton.setContentAreaFilled(false);
        helpJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpJButtonMouseExited(evt);
            }
        });
        helpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(helpJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(featuresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(featuresPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(helpJButton)
                    .addComponent(exitButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Export the protein features to file.
     *
     * @param evt
     */
    private void proteinExportAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proteinExportAllActionPerformed
        outputGenerator.getProteinsOutput(this, null, false, proteinValidated.isSelected(), proteinAccession.isSelected(), true, proteinPI.isSelected(),
                proteinDescription.isSelected(), proteinNPeptides.isSelected(), proteinEmpai.isSelected(), proteinSequenceCoverage.isSelected(), ptmSummary.isSelected(),
                proteinNSpectra.isSelected(), proteinNsaf.isSelected(), proteinScore.isSelected(), proteinConfidence.isSelected(), molecularWeight.isSelected(), true, proteinStarred.isSelected(),
                true, proteinHidden.isSelected());
    }//GEN-LAST:event_proteinExportAllActionPerformed

    /**
     * Export all peptide features to file.
     *
     * @param evt
     */
    private void peptideExportAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peptideExportAllActionPerformed
        outputGenerator.getPeptidesOutput(this, null, null, false, peptideValidated.isSelected(),
                peptideAccession.isSelected(), proteinDescriptionPeptideTab.isSelected(), peptidePosition.isSelected(), peptideSurroundingAA.isSelected(), peptideSequence.isSelected(),
                peptideModification.isSelected(), peptideLocation.isSelected(), precursorCharges.isSelected(), peptideNSpectra.isSelected(),
                peptideScore.isSelected(), peptideConfidence.isSelected(), true, peptideStarred.isSelected(), peptideHidden.isSelected(), peptideUniqueOnly.isSelected(), null);

    }//GEN-LAST:event_peptideExportAllActionPerformed

    /**
     * Export all psm features to file.
     *
     * @param evt
     */
    private void psmExportAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psmExportAllActionPerformed
        outputGenerator.getPSMsOutput(this, null, false, psmValidated.isSelected(), psmAccession.isSelected(), proteinDescriptionPsmTab.isSelected(), psmSequence.isSelected(),
                psmModification.isSelected(), psmLocation.isSelected(), psmFile.isSelected(), psmTitle.isSelected(),
                psmPrecursor.isSelected(), psmScore.isSelected(), psmConfidence.isSelected(), true, psmStarred.isSelected(), psmHidden.isSelected());
    }//GEN-LAST:event_psmExportAllActionPerformed

    /**
     * Export all search engine features to file.
     *
     * @param evt
     */
    private void assumptionExportAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assumptionExportAllActionPerformed
        outputGenerator.getAssumptionsOutput(this, null, assumptionValidated.isSelected(), assumptionAccession.isSelected(), proteinDescriptionSerarchEnginesTab.isSelected(),
                assumptionSequence.isSelected(), assumptionModification.isSelected(), assumptionFile.isSelected(), assumptionTitle.isSelected(),
                assumptionPrecursor.isSelected(), assumptionScores.isSelected(), assumptionConfidence.isSelected(), true);
    }//GEN-LAST:event_assumptionExportAllActionPerformed

    /**
     * Export all features to file.
     *
     * @param evt
     */
    private void exportAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportAllActionPerformed

        final JFileChooser fileChooser = new JFileChooser(peptideShakerGUI.getLastSelectedFolder());
        fileChooser.setDialogTitle("Select Result Folder");
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        FileFilter filter = new FileFilter() {

            @Override
            public boolean accept(File myFile) {
                return myFile.isDirectory();
            }

            @Override
            public String getDescription() {
                return "(Tab separated text file) *.txt";
            }
        };

        fileChooser.setFileFilter(filter);

        int returnVal = fileChooser.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {

            peptideShakerGUI.setLastSelectedFolder(fileChooser.getSelectedFile().getAbsolutePath());

            final FeaturesPreferencesDialog tempRef = this; // needed due to threading issues

            progressDialog = new ProgressDialogX(peptideShakerGUI,
                    Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/peptide-shaker.gif")),
                    Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/peptide-shaker-orange.gif")),
                    true);
            progressDialog.setIndeterminate(true);
            progressDialog.setTitle("Exporting. Please Wait...");


            new Thread(new Runnable() {

                public void run() {
                    try {
                        progressDialog.setVisible(true);
                    } catch (IndexOutOfBoundsException e) {
                        // ignore
                    }
                }
            }, "ProgressDialog").start();

            new Thread("SaveThread") {

                @Override
                public void run() {

                    CsvExporter exporter = new CsvExporter(peptideShakerGUI.getExperiment(), peptideShakerGUI.getSample(),
                            peptideShakerGUI.getReplicateNumber(), peptideShakerGUI.getSearchParameters().getEnzyme(), peptideShakerGUI.getIdentificationFeaturesGenerator());
                    boolean exported = exporter.exportResults(progressDialog, fileChooser.getSelectedFile());

                    boolean processCancelled = progressDialog.isRunCanceled();
                    progressDialog.setRunFinished();

                    if (!processCancelled) {

                        if (exported) {
                            JOptionPane.showMessageDialog(tempRef, "Identification results saved to folder \'" + fileChooser.getSelectedFile().getName() + "\'.",
                                    "Save Complete", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(tempRef, "An error occured during saving. See resources/conf/PeptideShaker.log for details.", "Save Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            }.start();
        }
    }//GEN-LAST:event_exportAllActionPerformed

    /**
     * Open the help dialog.
     *
     * @param evt
     */
    private void helpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpJButtonActionPerformed
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        new HelpDialog(peptideShakerGUI, getClass().getResource("/helpFiles/FeatureExport.html"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_helpJButtonActionPerformed

    /**
     * Change the cursor back to a hand icon.
     *
     * @param evt
     */
    private void helpJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpJButtonMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_helpJButtonMouseEntered

    /**
     * Change the cursor back to the default icon.
     *
     * @param evt
     */
    private void helpJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpJButtonMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_helpJButtonMouseExited

    /**
     * Close the dialog.
     *
     * @param evt
     */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * Select all protein features.
     *
     * @param evt
     */
    private void proteinSelectAllLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proteinSelectAllLabelMouseClicked
        proteinAccession.setSelected(true);
        proteinPI.setSelected(true);
        proteinDescription.setSelected(true);
        proteinNPeptides.setSelected(true);
        proteinEmpai.setSelected(true);
        proteinNSpectra.setSelected(true);
        ptmSummary.setSelected(true);
        proteinNsaf.setSelected(true);
        proteinScore.setSelected(true);
        proteinConfidence.setSelected(true);
        proteinSequenceCoverage.setSelected(true);
        proteinValidated.setSelected(true);
    }//GEN-LAST:event_proteinSelectAllLabelMouseClicked

    /**
     * Change the cursor back to a hand icon.
     *
     * @param evt
     */
    private void proteinSelectAllLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proteinSelectAllLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_proteinSelectAllLabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     *
     * @param evt
     */
    private void proteinSelectAllLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proteinSelectAllLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_proteinSelectAllLabelMouseExited

    /**
     * Deselect all protein features.
     *
     * @param evt
     */
    private void proteinDeselectAllLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proteinDeselectAllLabelMouseClicked
        proteinAccession.setSelected(false);
        proteinPI.setSelected(false);
        proteinDescription.setSelected(false);
        proteinNPeptides.setSelected(false);
        proteinEmpai.setSelected(false);
        proteinNSpectra.setSelected(false);
        proteinNsaf.setSelected(false);
        proteinScore.setSelected(false);
        proteinConfidence.setSelected(false);
        proteinSequenceCoverage.setSelected(false);
        ptmSummary.setSelected(false);
        proteinValidated.setSelected(false);
        proteinStarred.setSelected(false);
        proteinHidden.setSelected(false);
    }//GEN-LAST:event_proteinDeselectAllLabelMouseClicked

    /**
     * Change the cursor back to a hand icon.
     *
     * @param evt
     */
    private void proteinDeselectAllLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proteinDeselectAllLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_proteinDeselectAllLabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     *
     * @param evt
     */
    private void proteinDeselectAllLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proteinDeselectAllLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_proteinDeselectAllLabelMouseExited

    /**
     * Select all peptide features.
     *
     * @param evt
     */
    private void peptideSelectAllLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peptideSelectAllLabelMouseClicked
        peptideAccession.setSelected(true);
        proteinDescriptionPeptideTab.setSelected(true);
        peptideSequence.setSelected(true);
        peptideModification.setSelected(true);
        peptideLocation.setSelected(true);
        peptideSurroundingAA.setSelected(true);
        precursorCharges.setSelected(true);
        peptideNSpectra.setSelected(true);
        peptideScore.setSelected(true);
        peptideConfidence.setSelected(true);
        peptideLocation.setSelected(true);
        peptidePosition.setSelected(true);
        peptideValidated.setSelected(true);
    }//GEN-LAST:event_peptideSelectAllLabelMouseClicked

    /**
     * Change the cursor back to a hand icon.
     *
     * @param evt
     */
    private void peptideSelectAllLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peptideSelectAllLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_peptideSelectAllLabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     *
     * @param evt
     */
    private void peptideSelectAllLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peptideSelectAllLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_peptideSelectAllLabelMouseExited

    /**
     * Deselect all peptide features.
     *
     * @param evt
     */
    private void peptideDeselectAllLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peptideDeselectAllLabelMouseClicked
        peptideAccession.setSelected(false);
        proteinDescriptionPeptideTab.setSelected(false);
        peptideSequence.setSelected(false);
        peptideModification.setSelected(false);
        peptideLocation.setSelected(false);
        peptideSurroundingAA.setSelected(false);
        peptideUniqueOnly.setSelected(false);
        precursorCharges.setSelected(false);
        peptideNSpectra.setSelected(false);
        peptideScore.setSelected(false);
        peptideConfidence.setSelected(false);
        peptideLocation.setSelected(false);
        peptidePosition.setSelected(false);
        peptideValidated.setSelected(false);
        peptideStarred.setSelected(false);
        peptideHidden.setSelected(false);
    }//GEN-LAST:event_peptideDeselectAllLabelMouseClicked

    /**
     * Change the cursor back to a hand icon.
     *
     * @param evt
     */
    private void peptideDeselectAllLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peptideDeselectAllLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_peptideDeselectAllLabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     *
     * @param evt
     */
    private void peptideDeselectAllLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peptideDeselectAllLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_peptideDeselectAllLabelMouseExited

    /**
     * Select all psm features.
     *
     * @param evt
     */
    private void psmSelectAllLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psmSelectAllLabelMouseClicked
        psmAccession.setSelected(true);
        proteinDescriptionPsmTab.setSelected(true);
        psmSequence.setSelected(true);
        psmModification.setSelected(true);
        psmLocation.setSelected(true);
        psmFile.setSelected(true);
        psmTitle.setSelected(true);
        psmPrecursor.setSelected(true);
        psmScore.setSelected(true);
        psmConfidence.setSelected(true);
        psmValidated.setSelected(true);
    }//GEN-LAST:event_psmSelectAllLabelMouseClicked

    private void psmSelectAllLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psmSelectAllLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_psmSelectAllLabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     *
     * @param evt
     */
    private void psmSelectAllLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psmSelectAllLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_psmSelectAllLabelMouseExited

    /**
     * Deselect all psm features.
     *
     * @param evt
     */
    private void psmDeselectAllLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psmDeselectAllLabelMouseClicked
        psmAccession.setSelected(false);
        proteinDescriptionPsmTab.setSelected(false);
        psmSequence.setSelected(false);
        psmModification.setSelected(false);
        psmLocation.setSelected(false);
        psmFile.setSelected(false);
        psmTitle.setSelected(false);
        psmPrecursor.setSelected(false);
        psmScore.setSelected(false);
        psmConfidence.setSelected(false);
        psmValidated.setSelected(false);
        psmStarred.setSelected(false);
        psmHidden.setSelected(false);
    }//GEN-LAST:event_psmDeselectAllLabelMouseClicked

    /**
     * Change the cursor back to a hand icon.
     *
     * @param evt
     */
    private void psmDeselectAllLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psmDeselectAllLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_psmDeselectAllLabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     *
     * @param evt
     */
    private void psmDeselectAllLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psmDeselectAllLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_psmDeselectAllLabelMouseExited

    /**
     * Select all search engine features.
     *
     * @param evt
     */
    private void searchEnginesSelectAllLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchEnginesSelectAllLabelMouseClicked
        assumptionAccession.setSelected(true);
        proteinDescriptionSerarchEnginesTab.setSelected(true);
        assumptionSequence.setSelected(true);
        assumptionModification.setSelected(true);
        assumptionFile.setSelected(true);
        assumptionTitle.setSelected(true);
        assumptionPrecursor.setSelected(true);
        assumptionScores.setSelected(true);
        assumptionConfidence.setSelected(true);
        assumptionValidated.setSelected(true);
    }//GEN-LAST:event_searchEnginesSelectAllLabelMouseClicked

    /**
     * Change the cursor back to a hand icon.
     *
     * @param evt
     */
    private void searchEnginesSelectAllLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchEnginesSelectAllLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_searchEnginesSelectAllLabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     *
     * @param evt
     */
    private void searchEnginesSelectAllLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchEnginesSelectAllLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_searchEnginesSelectAllLabelMouseExited

    /**
     * Deselect all search engine features.
     *
     * @param evt
     */
    private void searchEnginesDeselectAllLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchEnginesDeselectAllLabelMouseClicked
        assumptionAccession.setSelected(false);
        proteinDescriptionSerarchEnginesTab.setSelected(false);
        assumptionSequence.setSelected(false);
        assumptionModification.setSelected(false);
        assumptionFile.setSelected(false);
        assumptionTitle.setSelected(false);
        assumptionPrecursor.setSelected(false);
        assumptionScores.setSelected(false);
        assumptionConfidence.setSelected(false);
        assumptionValidated.setSelected(false);
    }//GEN-LAST:event_searchEnginesDeselectAllLabelMouseClicked

    /**
     * Change the cursor back to a hand icon.
     *
     * @param evt
     */
    private void searchEnginesDeselectAllLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchEnginesDeselectAllLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_searchEnginesDeselectAllLabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     *
     * @param evt
     */
    private void searchEnginesDeselectAllLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchEnginesDeselectAllLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_searchEnginesDeselectAllLabelMouseExited
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox assumptionAccession;
    private javax.swing.JCheckBox assumptionConfidence;
    private javax.swing.JButton assumptionExportAll;
    private javax.swing.JCheckBox assumptionFile;
    private javax.swing.JCheckBox assumptionModification;
    private javax.swing.JCheckBox assumptionPrecursor;
    private javax.swing.JCheckBox assumptionScores;
    private javax.swing.JCheckBox assumptionSequence;
    private javax.swing.JCheckBox assumptionTitle;
    private javax.swing.JCheckBox assumptionValidated;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exportAll;
    private javax.swing.JPanel featuresPanel;
    private javax.swing.JButton helpJButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox molecularWeight;
    private javax.swing.JCheckBox peptideAccession;
    private javax.swing.JCheckBox peptideConfidence;
    private javax.swing.JLabel peptideDeselectAllLabel;
    private javax.swing.JButton peptideExportAll;
    private javax.swing.JCheckBox peptideHidden;
    private javax.swing.JCheckBox peptideLocation;
    private javax.swing.JCheckBox peptideModification;
    private javax.swing.JCheckBox peptideNSpectra;
    private javax.swing.JCheckBox peptidePosition;
    private javax.swing.JCheckBox peptideScore;
    private javax.swing.JLabel peptideSelectAllLabel;
    private javax.swing.JCheckBox peptideSequence;
    private javax.swing.JCheckBox peptideStarred;
    private javax.swing.JCheckBox peptideSurroundingAA;
    private javax.swing.JCheckBox peptideUniqueOnly;
    private javax.swing.JCheckBox peptideValidated;
    private javax.swing.JPanel peptidesPanel;
    private javax.swing.JCheckBox precursorCharges;
    private javax.swing.JPanel projectPanel;
    private javax.swing.JCheckBox proteinAccession;
    private javax.swing.JCheckBox proteinConfidence;
    private javax.swing.JCheckBox proteinDescription;
    private javax.swing.JCheckBox proteinDescriptionPeptideTab;
    private javax.swing.JCheckBox proteinDescriptionPsmTab;
    private javax.swing.JCheckBox proteinDescriptionSerarchEnginesTab;
    private javax.swing.JLabel proteinDeselectAllLabel;
    private javax.swing.JCheckBox proteinEmpai;
    private javax.swing.JButton proteinExportAll;
    private javax.swing.JCheckBox proteinHidden;
    private javax.swing.JCheckBox proteinNPeptides;
    private javax.swing.JCheckBox proteinNSpectra;
    private javax.swing.JCheckBox proteinNsaf;
    private javax.swing.JCheckBox proteinPI;
    private javax.swing.JCheckBox proteinScore;
    private javax.swing.JCheckBox proteinScore1;
    private javax.swing.JLabel proteinSelectAllLabel;
    private javax.swing.JCheckBox proteinSequenceCoverage;
    private javax.swing.JCheckBox proteinStarred;
    private javax.swing.JCheckBox proteinValidated;
    private javax.swing.JPanel proteinsPanel;
    private javax.swing.JCheckBox psmAccession;
    private javax.swing.JCheckBox psmConfidence;
    private javax.swing.JLabel psmDeselectAllLabel;
    private javax.swing.JButton psmExportAll;
    private javax.swing.JCheckBox psmFile;
    private javax.swing.JCheckBox psmHidden;
    private javax.swing.JCheckBox psmLocation;
    private javax.swing.JCheckBox psmModification;
    private javax.swing.JPanel psmPanel;
    private javax.swing.JCheckBox psmPrecursor;
    private javax.swing.JCheckBox psmScore;
    private javax.swing.JLabel psmSelectAllLabel;
    private javax.swing.JCheckBox psmSequence;
    private javax.swing.JCheckBox psmStarred;
    private javax.swing.JCheckBox psmTitle;
    private javax.swing.JCheckBox psmValidated;
    private javax.swing.JCheckBox ptmSummary;
    private javax.swing.JPanel searchEnginePanel;
    private javax.swing.JLabel searchEnginesDeselectAllLabel;
    private javax.swing.JLabel searchEnginesSelectAllLabel;
    private javax.swing.JLabel slashLabel1;
    private javax.swing.JLabel slashLabel2;
    private javax.swing.JLabel slashLabel3;
    private javax.swing.JLabel slashLabel4;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
