package eu.isas.peptideshaker.gui.tabpanels;

import com.compomics.util.experiment.biology.Protein;
import com.compomics.util.experiment.identification.SequenceFactory;
import com.compomics.util.gui.dialogs.ProgressDialogParent;
import com.compomics.util.gui.dialogs.ProgressDialogX;
import com.compomics.util.protein.Header.DatabaseType;
import eu.isas.peptideshaker.export.FeaturesGenerator;
import eu.isas.peptideshaker.gui.PeptideShakerGUI;
import eu.isas.peptideshaker.utils.BareBonesBrowserLaunch;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import uk.ac.ebi.kraken.interfaces.uniprot.UniProtEntry;
import uk.ac.ebi.kraken.interfaces.uniprot.description.FieldType;
import uk.ac.ebi.kraken.interfaces.uniprot.description.Name;
import uk.ac.ebi.kraken.uuw.services.remoting.EntryIterator;
import uk.ac.ebi.kraken.uuw.services.remoting.Query;
import uk.ac.ebi.kraken.uuw.services.remoting.RemoteDataAccessException;
import uk.ac.ebi.kraken.uuw.services.remoting.UniProtJAPI;
import uk.ac.ebi.kraken.uuw.services.remoting.UniProtQueryBuilder;
import uk.ac.ebi.kraken.uuw.services.remoting.UniProtQueryService;

/**
 * This tab contains the basic protein annotation and links to other 
 * protein resources.
 * 
 * @author Harald Barsnes
 */
public class AnnotationPanel extends javax.swing.JPanel implements ProgressDialogParent {

    /**
     * The current protein accession number.
     */
    private String currentAccessionNumber = "";
    /**
     * A progress dialog.
     */
    private ProgressDialogX progressDialog;
    /**
     * The PeptideShakerGUI parent.
     */
    private PeptideShakerGUI peptideShakerGUI;
    /**
     * The sequence factory
     */
    private SequenceFactory sequenceFactory = SequenceFactory.getInstance();

    /** 
     * Creates a new AnnotationPanel.
     * 
     * @param peptideShakerGUI
     */
    public AnnotationPanel(PeptideShakerGUI peptideShakerGUI) {
        initComponents();
        this.peptideShakerGUI = peptideShakerGUI;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        annotationLinksJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        accessionNumberJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        proteinNameJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        geneNameJTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        taxonomyJTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        databaseJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        altProteinNameJTextField = new javax.swing.JTextField();
        annotationLinksJPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        loadUniProtJButton = new javax.swing.JButton();
        webUniProtLabel = new javax.swing.JLabel();
        annotationLinksJPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        loadDastyJButton = new javax.swing.JButton();
        webDasty3Label = new javax.swing.JLabel();
        annotationLinksJPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        loadReactomeJButton = new javax.swing.JButton();
        webReactomeLabel = new javax.swing.JLabel();
        annotationLinksJPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        loadStringJButton = new javax.swing.JButton();
        webStringLabel = new javax.swing.JLabel();
        annotationLinksJPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        loadDavidJButton = new javax.swing.JButton();
        webDavidLabel = new javax.swing.JLabel();
        annotationLinksJPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        loadIntActJButton = new javax.swing.JButton();
        webIntActLabel = new javax.swing.JLabel();
        annotationLinksJPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        loadQuickGOJButton = new javax.swing.JButton();
        webQuickGOLabel = new javax.swing.JLabel();
        annotationLinksJPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        loadInterProJButton = new javax.swing.JButton();
        webInterProLabel = new javax.swing.JLabel();
        helpPanel = new javax.swing.JPanel();
        helpScrollPane = new javax.swing.JScrollPane();
        helpEditorPane = new javax.swing.JEditorPane();
        warningJLabel = new javax.swing.JLabel();
        picrLinkJLabel = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(255, 255, 255));

        annotationLinksJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic Protein Annotation"));
        annotationLinksJPanel.setOpaque(false);

        jLabel1.setText("Accession Number:");

        accessionNumberJTextField.setEditable(false);

        jLabel3.setText("Protein Name:");

        proteinNameJTextField.setEditable(false);

        jLabel4.setText("Gene Name:");

        geneNameJTextField.setEditable(false);

        jLabel8.setText("Taxonomy:");

        taxonomyJTextField.setEditable(false);

        jLabel16.setText("Database:");

        databaseJTextField.setEditable(false);

        jLabel6.setText("Alt. Names:");
        jLabel6.setToolTipText("Alternative Protein Names");

        altProteinNameJTextField.setEditable(false);

        javax.swing.GroupLayout annotationLinksJPanelLayout = new javax.swing.GroupLayout(annotationLinksJPanel);
        annotationLinksJPanel.setLayout(annotationLinksJPanelLayout);
        annotationLinksJPanelLayout.setHorizontalGroup(
            annotationLinksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(annotationLinksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16))
                .addGap(38, 38, 38)
                .addGroup(annotationLinksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(databaseJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(taxonomyJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(geneNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(altProteinNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(proteinNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(accessionNumberJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
                .addContainerGap())
        );

        annotationLinksJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel3, jLabel6, jLabel8});

        annotationLinksJPanelLayout.setVerticalGroup(
            annotationLinksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(annotationLinksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accessionNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(annotationLinksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proteinNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(annotationLinksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altProteinNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(annotationLinksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geneNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(annotationLinksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxonomyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(annotationLinksJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(databaseJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap())
        );

        annotationLinksJPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("UniProt - protein knowledgebase"));
        annotationLinksJPanel1.setOpaque(false);

        jLabel5.setText("High-quality protein sequence and functional information.");

        loadUniProtJButton.setText("Search UniProt");
        loadUniProtJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadUniProtJButtonActionPerformed(evt);
            }
        });

        webUniProtLabel.setText("<html> <a href=\\\"dummy_link\">web</a></html>");
        webUniProtLabel.setToolTipText("Open the UniProt web page");
        webUniProtLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webUniProtLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                webUniProtLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                webUniProtLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout annotationLinksJPanel1Layout = new javax.swing.GroupLayout(annotationLinksJPanel1);
        annotationLinksJPanel1.setLayout(annotationLinksJPanel1Layout);
        annotationLinksJPanel1Layout.setHorizontalGroup(
            annotationLinksJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadUniProtJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(webUniProtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        annotationLinksJPanel1Layout.setVerticalGroup(
            annotationLinksJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(annotationLinksJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadUniProtJButton)
                    .addComponent(jLabel5)
                    .addComponent(webUniProtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        annotationLinksJPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dasty 3 - protein sequence features"));
        annotationLinksJPanel2.setOpaque(false);

        jLabel7.setText("Web client for visualizing protein sequence feature information.");

        loadDastyJButton.setText("Search Dasty 3");
        loadDastyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDastyJButtonActionPerformed(evt);
            }
        });

        webDasty3Label.setText("<html> <a href=\\\"dummy_link\">web</a></html>");
        webDasty3Label.setToolTipText("Open the Dasty3 web page");
        webDasty3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webDasty3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                webDasty3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                webDasty3LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout annotationLinksJPanel2Layout = new javax.swing.GroupLayout(annotationLinksJPanel2);
        annotationLinksJPanel2.setLayout(annotationLinksJPanel2Layout);
        annotationLinksJPanel2Layout.setHorizontalGroup(
            annotationLinksJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadDastyJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(webDasty3Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        annotationLinksJPanel2Layout.setVerticalGroup(
            annotationLinksJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(annotationLinksJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadDastyJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(webDasty3Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        annotationLinksJPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Reactome - pathway database"));
        annotationLinksJPanel3.setOpaque(false);

        jLabel9.setText("Manually curated and peer-reviewed pathway database.");

        loadReactomeJButton.setText("Search Reactome");
        loadReactomeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadReactomeJButtonActionPerformed(evt);
            }
        });

        webReactomeLabel.setText("<html> <a href=\\\"dummy_link\">web</a></html>");
        webReactomeLabel.setToolTipText("Open the Reactome web page");
        webReactomeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webReactomeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                webReactomeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                webReactomeLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout annotationLinksJPanel3Layout = new javax.swing.GroupLayout(annotationLinksJPanel3);
        annotationLinksJPanel3.setLayout(annotationLinksJPanel3Layout);
        annotationLinksJPanel3Layout.setHorizontalGroup(
            annotationLinksJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadReactomeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(webReactomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        annotationLinksJPanel3Layout.setVerticalGroup(
            annotationLinksJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(annotationLinksJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(loadReactomeJButton)
                    .addComponent(webReactomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        annotationLinksJPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("STRING - protein interaction"));
        annotationLinksJPanel4.setOpaque(false);

        jLabel10.setText("Known and Predicted Protein-Protein Interactions.");

        loadStringJButton.setText("Search STRING");
        loadStringJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadStringJButtonActionPerformed(evt);
            }
        });

        webStringLabel.setText("<html> <a href=\\\"dummy_link\">web</a></html>");
        webStringLabel.setToolTipText("Open the STRING web page");
        webStringLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webStringLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                webStringLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                webStringLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout annotationLinksJPanel4Layout = new javax.swing.GroupLayout(annotationLinksJPanel4);
        annotationLinksJPanel4.setLayout(annotationLinksJPanel4Layout);
        annotationLinksJPanel4Layout.setHorizontalGroup(
            annotationLinksJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadStringJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(webStringLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        annotationLinksJPanel4Layout.setVerticalGroup(
            annotationLinksJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(annotationLinksJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(loadStringJButton)
                    .addComponent(webStringLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        annotationLinksJPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("DAVID - functional annotation"));
        annotationLinksJPanel5.setOpaque(false);

        jLabel11.setText("Database for Annotation, Visualization and Integrated Discovery.");

        loadDavidJButton.setText("Search DAVID");
        loadDavidJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDavidJButtonActionPerformed(evt);
            }
        });

        webDavidLabel.setText("<html> <a href=\\\"dummy_link\">web</a></html>");
        webDavidLabel.setToolTipText("Open the DAVID web page");
        webDavidLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webDavidLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                webDavidLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                webDavidLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout annotationLinksJPanel5Layout = new javax.swing.GroupLayout(annotationLinksJPanel5);
        annotationLinksJPanel5.setLayout(annotationLinksJPanel5Layout);
        annotationLinksJPanel5Layout.setHorizontalGroup(
            annotationLinksJPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadDavidJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(webDavidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        annotationLinksJPanel5Layout.setVerticalGroup(
            annotationLinksJPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(annotationLinksJPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(loadDavidJButton)
                    .addComponent(webDavidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        annotationLinksJPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("IntAct - protein interaction"));
        annotationLinksJPanel6.setOpaque(false);

        jLabel12.setText("Analysis tools for protein interaction data.");

        loadIntActJButton.setText("Search IntAct");
        loadIntActJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadIntActJButtonActionPerformed(evt);
            }
        });

        webIntActLabel.setText("<html> <a href=\\\"dummy_link\">web</a></html>");
        webIntActLabel.setToolTipText("Open the IntAct web page");
        webIntActLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webIntActLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                webIntActLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                webIntActLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout annotationLinksJPanel6Layout = new javax.swing.GroupLayout(annotationLinksJPanel6);
        annotationLinksJPanel6.setLayout(annotationLinksJPanel6Layout);
        annotationLinksJPanel6Layout.setHorizontalGroup(
            annotationLinksJPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadIntActJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(webIntActLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        annotationLinksJPanel6Layout.setVerticalGroup(
            annotationLinksJPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(annotationLinksJPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(loadIntActJButton)
                    .addComponent(webIntActLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        annotationLinksJPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("QuickGO - gene ontology terms and annotations"));
        annotationLinksJPanel7.setOpaque(false);

        jLabel13.setText("Web-based browser for Gene Ontology terms.");

        loadQuickGOJButton.setText("Search QuickGO");
        loadQuickGOJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadQuickGOJButtonActionPerformed(evt);
            }
        });

        webQuickGOLabel.setText("<html> <a href=\\\"dummy_link\">web</a></html>");
        webQuickGOLabel.setToolTipText("Open the QuickGO web page");
        webQuickGOLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webQuickGOLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                webQuickGOLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                webQuickGOLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout annotationLinksJPanel7Layout = new javax.swing.GroupLayout(annotationLinksJPanel7);
        annotationLinksJPanel7.setLayout(annotationLinksJPanel7Layout);
        annotationLinksJPanel7Layout.setHorizontalGroup(
            annotationLinksJPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadQuickGOJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(webQuickGOLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        annotationLinksJPanel7Layout.setVerticalGroup(
            annotationLinksJPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(annotationLinksJPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(loadQuickGOJButton)
                    .addComponent(webQuickGOLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        annotationLinksJPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("InterPro - predictive protein signatures"));
        annotationLinksJPanel8.setOpaque(false);

        jLabel14.setText("Integrated database of predictive protein signatures.");

        loadInterProJButton.setText("Search InterPro");
        loadInterProJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadInterProJButtonActionPerformed(evt);
            }
        });

        webInterProLabel.setText("<html> <a href=\\\"dummy_link\">web</a></html>");
        webInterProLabel.setToolTipText("Open the InterPro web page");
        webInterProLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webInterProLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                webInterProLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                webInterProLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout annotationLinksJPanel8Layout = new javax.swing.GroupLayout(annotationLinksJPanel8);
        annotationLinksJPanel8.setLayout(annotationLinksJPanel8Layout);
        annotationLinksJPanel8Layout.setHorizontalGroup(
            annotationLinksJPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadInterProJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(webInterProLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        annotationLinksJPanel8Layout.setVerticalGroup(
            annotationLinksJPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annotationLinksJPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(annotationLinksJPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(loadInterProJButton)
                    .addComponent(webInterProLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        helpPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Protein Annotation - Help"));
        helpPanel.setOpaque(false);

        helpScrollPane.setBorder(null);
        helpScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        helpScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        helpEditorPane.setContentType("text/html");
        helpEditorPane.setEditable(false);
        helpEditorPane.setText("<html>\n<b>Single Protein</b><br>\nTo access the annotations for the currently selected protein, simply click the button corresponding to the \nwanted resource.\n<br><br><br>\n<b>Multiple Proteins</b><br>\nTo get the list of all validated proteins in your project click <a href=\"validated_proteins\">here</a>.<br>\nAdvanced export options: <i>Export</i> > <i>Identification Features</i>. \n<br><br>\nTo querry using multiple proteins, click the <a href=\"dummy_link\">web</a> link next to the resource and \nfollow the instructions provided at the resource web page.\n</html>");
        helpEditorPane.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                helpEditorPaneHyperlinkUpdate(evt);
            }
        });
        helpScrollPane.setViewportView(helpEditorPane);

        javax.swing.GroupLayout helpPanelLayout = new javax.swing.GroupLayout(helpPanel);
        helpPanel.setLayout(helpPanelLayout);
        helpPanelLayout.setHorizontalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        helpPanelLayout.setVerticalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        warningJLabel.setFont(warningJLabel.getFont().deriveFont((warningJLabel.getFont().getStyle() | java.awt.Font.ITALIC)));
        warningJLabel.setForeground(new java.awt.Color(255, 0, 0));
        warningJLabel.setText(" ");

        picrLinkJLabel.setText("<html><a href=\\\"dummy_link\\\">PICR - Protein Identifier Cross-Reference Service</a></html>");
        picrLinkJLabel.setToolTipText("<html>\nMap protein identifiers across<br>\nmultiple source databases\n</html>");
        picrLinkJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                picrLinkJLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                picrLinkJLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                picrLinkJLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(warningJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picrLinkJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(annotationLinksJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(annotationLinksJPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(annotationLinksJPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(annotationLinksJPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(annotationLinksJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(annotationLinksJPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(annotationLinksJPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(annotationLinksJPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(annotationLinksJPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(helpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(annotationLinksJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(helpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(annotationLinksJPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annotationLinksJPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annotationLinksJPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annotationLinksJPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(annotationLinksJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annotationLinksJPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annotationLinksJPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annotationLinksJPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warningJLabel)
                    .addComponent(picrLinkJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Open the protein accession in Dasty3.
     * 
     * @param evt 
     */
    private void loadDastyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadDastyJButtonActionPerformed
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://www.ebi.ac.uk/dasty/client/index.html?q=" + accessionNumberJTextField.getText());
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_loadDastyJButtonActionPerformed

    /**
     * Open the protein accession in UniProt.
     * 
     * @param evt 
     */
    private void loadUniProtJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadUniProtJButtonActionPerformed
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://www.uniprot.org/uniprot/" + accessionNumberJTextField.getText());
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_loadUniProtJButtonActionPerformed

    /**
     * Open the protein accession in Reactome.
     * 
     * @param evt 
     */
    private void loadReactomeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadReactomeJButtonActionPerformed
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://www.reactome.org/cgi-bin/link?SOURCE=UNIPROT&ID=" + accessionNumberJTextField.getText());
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_loadReactomeJButtonActionPerformed

    /**
     * Open the protein accession in STRING.
     * 
     * @param evt 
     */
    private void loadStringJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadStringJButtonActionPerformed
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://string-db.org/newstring_cgi/show_input_page.pl?identifier=" + accessionNumberJTextField.getText());
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_loadStringJButtonActionPerformed

    /**
     * Open the protein accession in DAVID.
     * 
     * @param evt 
     */
    private void loadDavidJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadDavidJButtonActionPerformed
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://david.abcc.ncifcrf.gov/api.jsp?type=UNIPROT_ACCESSION&ids=" + accessionNumberJTextField.getText() + "&tool=summary");
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_loadDavidJButtonActionPerformed

    /**
     * Open the protein accession in IntAct.
     * 
     * @param evt 
     */
    private void loadIntActJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadIntActJButtonActionPerformed
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://www.ebi.ac.uk/intact/pages/interactions/interactions.xhtml?query=" + accessionNumberJTextField.getText());
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_loadIntActJButtonActionPerformed

    /**
     * Open the protein accession in QuickGO.
     * 
     * @param evt 
     */
    private void loadQuickGOJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadQuickGOJButtonActionPerformed
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://www.ebi.ac.uk/QuickGO/GSearch?q=" + accessionNumberJTextField.getText() + "&what=Protein");
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_loadQuickGOJButtonActionPerformed

    /**
     * Open the protein accession in InterPro.
     * 
     * @param evt 
     */
    private void loadInterProJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadInterProJButtonActionPerformed
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://www.ebi.ac.uk/interpro/ISearch?query=" + accessionNumberJTextField.getText());
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_loadInterProJButtonActionPerformed

    /**
     * Open the Dasty 3 web page.
     * 
     * @param evt 
     */
    private void webDasty3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webDasty3LabelMouseClicked
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://www.ebi.ac.uk/dasty");
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webDasty3LabelMouseClicked

    /**
     * Change the cursor icon to a hand icon.
     * 
     * @param evt 
     */
    private void webDasty3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webDasty3LabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_webDasty3LabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     * 
     * @param evt 
     */
    private void webDasty3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webDasty3LabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webDasty3LabelMouseExited

    /**
     * Open the UniProt web page.
     * 
     * @param evt 
     */
    private void webUniProtLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webUniProtLabelMouseClicked
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://www.uniprot.org");
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webUniProtLabelMouseClicked

    /**
     * Change the cursor icon to a hand icon.
     * 
     * @param evt 
     */
    private void webUniProtLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webUniProtLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_webUniProtLabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     * 
     * @param evt 
     */
    private void webUniProtLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webUniProtLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webUniProtLabelMouseExited

    /**
     * Open the Reactome web page.
     * 
     * @param evt 
     */
    private void webReactomeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webReactomeLabelMouseClicked
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://www.reactome.org");
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webReactomeLabelMouseClicked

    /**
     * Change the cursor icon to a hand icon.
     * 
     * @param evt 
     */
    private void webReactomeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webReactomeLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_webReactomeLabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     * 
     * @param evt 
     */
    private void webReactomeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webReactomeLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webReactomeLabelMouseExited

    /**
     * Open the STRING web page.
     * 
     * @param evt 
     */
    private void webStringLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webStringLabelMouseClicked
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://string-db.org");
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webStringLabelMouseClicked

    /**
     * Change the cursor icon to a hand icon.
     * 
     * @param evt 
     */
    private void webStringLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webStringLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_webStringLabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     * 
     * @param evt 
     */
    private void webStringLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webStringLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webStringLabelMouseExited

    /**
     * Open the QuickGO web page.
     * 
     * @param evt 
     */
    private void webQuickGOLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webQuickGOLabelMouseClicked
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://www.ebi.ac.uk/QuickGO");
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webQuickGOLabelMouseClicked

    /**
     * Change the cursor icon to a hand icon.
     * 
     * @param evt 
     */
    private void webQuickGOLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webQuickGOLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_webQuickGOLabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     * 
     * @param evt 
     */
    private void webQuickGOLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webQuickGOLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webQuickGOLabelMouseExited

    /**
     * Open the InterPro web page.
     * 
     * @param evt 
     */
    private void webInterProLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webInterProLabelMouseClicked
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://www.ebi.ac.uk/interpro");
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webInterProLabelMouseClicked

    /**
     * Change the cursor icon to a hand icon.
     * 
     * @param evt 
     */
    private void webInterProLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webInterProLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_webInterProLabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     * 
     * @param evt 
     */
    private void webInterProLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webInterProLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webInterProLabelMouseExited

    /**
     * Open the IntAct web page.
     * 
     * @param evt 
     */
    private void webIntActLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webIntActLabelMouseClicked
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://www.ebi.ac.uk/intact");
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webIntActLabelMouseClicked

    /**
     * Change the cursor icon to a hand icon.
     * 
     * @param evt 
     */
    private void webIntActLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webIntActLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_webIntActLabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     * 
     * @param evt 
     */
    private void webIntActLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webIntActLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webIntActLabelMouseExited

    /**
     * Enable the hyperlinks in the help panel.
     * 
     * @param evt 
     */
    private void helpEditorPaneHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_helpEditorPaneHyperlinkUpdate
        if (evt.getEventType().toString().equalsIgnoreCase(
                javax.swing.event.HyperlinkEvent.EventType.ACTIVATED.toString())) {

            if (evt.getDescription().equalsIgnoreCase("validated_proteins")) {

                if (peptideShakerGUI.getIdentification() != null) {

                    progressDialog = new ProgressDialogX(peptideShakerGUI, peptideShakerGUI, true);
                    progressDialog.doNothingOnClose();

                    final AnnotationPanel tempRef = this; // needed due to threading issues

                    new Thread(new Runnable() {

                        public void run() {
                            progressDialog.setIndeterminate(true);
                            progressDialog.setTitle("Getting Accession Numbers. Please Wait...");
                            progressDialog.setVisible(true);
                        }
                    }, "ProgressDialog").start();

                    new Thread("AccessionNumberThread") {

                        @Override
                        public void run() {

                            String feature = "";

                            FeaturesGenerator outputGenerator = new FeaturesGenerator(peptideShakerGUI);

                            try {
                                feature = outputGenerator.getProteinsOutput(progressDialog, null, false, true, true, false,
                                        false, false, false, false, false,
                                        false, false, false, false);
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(tempRef, "An error occurred while generating the output.", "Output Error.", JOptionPane.ERROR_MESSAGE);
                                e.printStackTrace();
                                feature = "";
                            }

                            StringSelection stringSelection = new StringSelection(feature);
                            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                            clipboard.setContents(stringSelection, peptideShakerGUI);

                            progressDialog.setVisible(false);
                            progressDialog.dispose();
                            JOptionPane.showMessageDialog(peptideShakerGUI, "Accession numbers copied to clipboard.", "Copied to Clipboard", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }.start();
                } else {
                    JOptionPane.showMessageDialog(peptideShakerGUI, "You have to load a project first!", "No Project", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_helpEditorPaneHyperlinkUpdate

    /**
     * Change the cursor back to the default icon.
     * 
     * @param evt 
     */
    private void webDavidLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webDavidLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webDavidLabelMouseExited

    /**
     * Change the cursor back to a hand icon.
     * 
     * @param evt 
     */
    private void webDavidLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webDavidLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_webDavidLabelMouseEntered

    /**
     * Open the DAVID web page.
     * 
     * @param evt 
     */
    private void webDavidLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webDavidLabelMouseClicked
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://david.abcc.ncifcrf.gov");
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_webDavidLabelMouseClicked

    /**
     * Change the cursor back to a hand icon.
     * 
     * @param evt 
     */
    private void picrLinkJLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picrLinkJLabelMouseEntered
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_picrLinkJLabelMouseEntered

    /**
     * Change the cursor back to the default icon.
     * 
     * @param evt 
     */
    private void picrLinkJLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picrLinkJLabelMouseExited
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_picrLinkJLabelMouseExited

    /**
     * Open the PICR web page.
     * 
     * @param evt 
     */
    private void picrLinkJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picrLinkJLabelMouseClicked
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BareBonesBrowserLaunch.openURL("http://www.ebi.ac.uk/Tools/picr/");
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_picrLinkJLabelMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accessionNumberJTextField;
    private javax.swing.JTextField altProteinNameJTextField;
    private javax.swing.JPanel annotationLinksJPanel;
    private javax.swing.JPanel annotationLinksJPanel1;
    private javax.swing.JPanel annotationLinksJPanel2;
    private javax.swing.JPanel annotationLinksJPanel3;
    private javax.swing.JPanel annotationLinksJPanel4;
    private javax.swing.JPanel annotationLinksJPanel5;
    private javax.swing.JPanel annotationLinksJPanel6;
    private javax.swing.JPanel annotationLinksJPanel7;
    private javax.swing.JPanel annotationLinksJPanel8;
    private javax.swing.JTextField databaseJTextField;
    private javax.swing.JTextField geneNameJTextField;
    private javax.swing.JEditorPane helpEditorPane;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JScrollPane helpScrollPane;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadDastyJButton;
    private javax.swing.JButton loadDavidJButton;
    private javax.swing.JButton loadIntActJButton;
    private javax.swing.JButton loadInterProJButton;
    private javax.swing.JButton loadQuickGOJButton;
    private javax.swing.JButton loadReactomeJButton;
    private javax.swing.JButton loadStringJButton;
    private javax.swing.JButton loadUniProtJButton;
    private javax.swing.JLabel picrLinkJLabel;
    private javax.swing.JTextField proteinNameJTextField;
    private javax.swing.JTextField taxonomyJTextField;
    private javax.swing.JLabel warningJLabel;
    private javax.swing.JLabel webDasty3Label;
    private javax.swing.JLabel webDavidLabel;
    private javax.swing.JLabel webIntActLabel;
    private javax.swing.JLabel webInterProLabel;
    private javax.swing.JLabel webQuickGOLabel;
    private javax.swing.JLabel webReactomeLabel;
    private javax.swing.JLabel webStringLabel;
    private javax.swing.JLabel webUniProtLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * Updates the basic protein annotation information.
     * 
     * @param aAccessionNumber the new accession number
     */
    public void updateBasicProteinAnnotation(String aAccessionNumber) {

        // only update if new accession number
        if (aAccessionNumber != null && !currentAccessionNumber.equalsIgnoreCase(aAccessionNumber)) {

            currentAccessionNumber = aAccessionNumber;
            accessionNumberJTextField.setText(currentAccessionNumber);

            progressDialog = new ProgressDialogX(peptideShakerGUI, this, true);

            new Thread(new Runnable() {

                public void run() {
                    progressDialog.setTitle("Loading Basic Protein Annotation. Please Wait...");
                    progressDialog.setIndeterminate(true);
                    progressDialog.setVisible(true);
                }
            }, "ProgressDialog").start();

            new Thread("BasicProteinDetailsThread") {

                @Override
                public void run() {

                    try {
                        Protein currentProtein = sequenceFactory.getProtein(currentAccessionNumber);
                        DatabaseType databaseType = currentProtein.getDatabaseType();

                        databaseJTextField.setText(databaseType.toString());

                        if (databaseType == DatabaseType.UniProt) {

                            UniProtQueryService queryService = UniProtJAPI.factory.getUniProtQueryService();
                            ArrayList<String> accessionNumbers = new ArrayList<String>();
                            accessionNumbers.add(currentAccessionNumber);

                            Query proteinQuery = UniProtQueryBuilder.buildIDListQuery(accessionNumbers);
                            EntryIterator<UniProtEntry> entries = queryService.getEntryIterator(proteinQuery);

                            Iterator<UniProtEntry> iterator = entries.iterator();

                            int counter = 0;

                            if (iterator.hasNext()) {

                                UniProtEntry uniProtEntry = iterator.next();

                                if (uniProtEntry.getProteinDescription().getRecommendedName().getFieldsByType(FieldType.FULL).size() > 0) {
                                    proteinNameJTextField.setText(uniProtEntry.getProteinDescription().getRecommendedName().getFieldsByType(FieldType.FULL).get(0).getValue());
                                } else {
                                    proteinNameJTextField.setText("(not available)");
                                }

                                List<Name> altNames = uniProtEntry.getProteinDescription().getAlternativeNames();

                                String altNamesAsString = "";
                                String altProteinNamesTooltip = "<html>";

                                for (int i = 0; i < altNames.size(); i++) {
                                    if (altNames.get(i).getFieldsByType(FieldType.FULL).size() > 0) {
                                        altNamesAsString += altNames.get(i).getFieldsByType(FieldType.FULL).get(0).getValue().toString() + ", ";
                                        altProteinNamesTooltip += altNames.get(i).getFieldsByType(FieldType.FULL).get(0).getValue().toString() + "<br>";
                                    }
                                }

                                if (altNamesAsString.endsWith(", ")) {
                                    altNamesAsString = altNamesAsString.substring(0, altNamesAsString.length() - 2);
                                }

                                if (altNamesAsString.length() > 0) {
                                    altProteinNamesTooltip += "</html>";
                                    altProteinNameJTextField.setToolTipText(altProteinNamesTooltip);
                                    altProteinNameJTextField.setText(altNamesAsString);
                                } else {
                                    altProteinNameJTextField.setToolTipText(null);
                                    altProteinNameJTextField.setText("(not available)");
                                }

                                geneNameJTextField.setText(uniProtEntry.getGenes().get(0).getGeneName().toString());

                                if (uniProtEntry.getOrganism().hasCommonName()) {
                                    taxonomyJTextField.setText(uniProtEntry.getOrganism().getCommonName().toString());
                                } else {
                                    taxonomyJTextField.setText(uniProtEntry.getOrganism().getScientificName().toString());
                                }

                                counter++;
                            }

                            if (iterator.hasNext()) {
                                counter++;
                            }

                            if (counter > 1) {
                                JOptionPane.showMessageDialog(peptideShakerGUI, "UniProt Error", "The accession number resulted in more than 1 hit!", JOptionPane.WARNING_MESSAGE);
                            } else if (counter == 0) {
                                JOptionPane.showMessageDialog(peptideShakerGUI, "UniProt Error", "The accession number resulted in 0 hits!", JOptionPane.WARNING_MESSAGE);
                            }

                            warningJLabel.setText("");
                        } else {
                            warningJLabel.setText("Warning: The annotation resources work best with UniProt accession numbers. Try using");
                            proteinNameJTextField.setText("Unknown");
                            altProteinNameJTextField.setText("Unknown");
                            geneNameJTextField.setText("Unknown");
                            taxonomyJTextField.setText("Unknown");
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    } catch (RemoteDataAccessException e) {
                        e.printStackTrace();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                    progressDialog.setVisible(false);
                    progressDialog.dispose();
                }
            }.start();
        }
    }

    @Override
    public void cancelProgress() {
        // do nothing??
        // @TODO: is this correct??
    }
}
